### PR TITLE
scale : add iperf command/test

### PR DESCRIPTION
**Pull request by nplanel**

### CODE REVIEW

**Comment by nplanel** [comment]
run skydive-functional-tests-backend-orientdb

**Comment by safchain** [comment]
rerun tests

**Comment by nplanel** [comment]
run skydive-scale-tests

**Comment by lebauce** [comment]
Could you please add the iperf package to this list https://github.com/skydive-project/skydive/blob/master/scripts/ci/ansible/deploy.yml#L79

**Comment by nplanel** [comment]
done

**Comment by nplanel** [comment]
run skydive-scale-tests

**Comment by safchain** [comment]
run skydive-scale-tests

**Comment by safchain** [comment]
run scale-tests

**Comment by safchain** [comment]
run scale-tests

**Comment by nplanel** [comment]
run skydive-scale-tests

**Pull request merged**
