### PR TITLE
Build : fix static and docker-image build

### PR DESCRIPTION
**Pull request by nplanel**
As libvirt can't be linked in static
User should not pass a special parameter in this case

### CODE REVIEW

**Comment by nplanel** [comment]
run python-tests

**Comment by nplanel** [comment]
run skydive-python-tests

**Comment by nplanel** [comment]
run skydive-python-tests

**Comment by lebauce** [comment]
run skydive-create-docker-images

**Comment by lebauce** [comment]
run skydive-python-tests

**Comment by nplanel** [comment]
run skydive-python-tests

**Comment by nplanel** [comment]
run skydive-create-docker-images

**Pull request merged**
