### PR TITLE
CI: switch to html logs

### PR DESCRIPTION
**Pull request by nplanel**

### CODE REVIEW

**Comment by lebauce** [comment]
We switched back to plain text logs because, sometimes, the HTML logs were not complete. I would prefer to fix the issue before switching back to HTML

**Comment by nplanel** [comment]
@lebauce the issues has been already fixed, with a summary header in html logs

**Comment by lebauce** [comment]
run skydive-functional-tests-backend-elasticsearch
run skydive-functional-tests-backend-orientdb

**Comment by lebauce** [comment]
@nplanel Ok, nice.

**Comment by lebauce** [comment]
run skydive-functional-tests-backend-elasticsearch

**Comment by lebauce** [comment]
run skydive-functional-tests-backend-orientdb

**Comment by lebauce** [comment]
run skydive-functional-tests-backend-orientdb

**Pull request merged**
