### PR TITLE
govendor : use latest version of github.com/kardianos/govendor

### PR DESCRIPTION
**Pull request by nplanel**

### CODE REVIEW

**Comment by nplanel** [comment]
which version of go did you use ? (I use go 1.9)

**Comment by nplanel** [comment]
same issue with go 16

**Comment by safchain** [comment]
version 1.8.3
@masco-enovance could you please test this to see if we you the same result as Nicolas

**Comment by safchain** [comment]
Seems to be OK regarding to the CI resutls

**Pull request merged**
