### PR TITLE
Implement partial updates

### PR DESCRIPTION
**Pull request by lebauce**

### CODE REVIEW

**Comment by lebauce** [comment]
run functional-tests-backend-orientdb

**Comment by lebauce** [comment]
run scale-tests
run cdd-overview-tests
run k8s-tests

**Comment by lebauce** [comment]
run scale-tests
run cdd-overview-tests
run k8s-tests

**Comment by lebauce** [comment]
run scale-tests

**Comment by lebauce** [comment]
run k8s-tests

**Comment by lebauce** [comment]
run functional-tests-backend-elasticsearch
run functional-tests-backend-orientdb

**Comment by lebauce** [comment]
run functional-tests-backend-orientdb

**Comment by lebauce** [comment]
run functional-tests-backend-orientdb

**Comment by lebauce** [comment]
run functional-tests-backend-orientdb

**Comment by lebauce** [comment]
run functional-tests-backend-orientdb

**Comment by lebauce** [comment]
run functional-tests-backend-orientdb

**Comment by lebauce** [comment]
run k8s-tests

**Comment by lebauce** [comment]
run functional-tests-backend-elasticsearch

**Comment by lebauce** [comment]
run python-tests

**Comment by lebauce** [comment]
run cdd-overview-tests

**Comment by lebauce** [comment]
run functional-tests-backend-orientdb

**Comment by lebauce** [comment]
run functional-tests-backend-orientdb

**Comment by lebauce** [comment]
run functional-tests-backend-elasticsearch

**Comment by lebauce** [comment]
run functional-tests-backend-elasticsearch

**Comment by safchain** [comment]
run skydive-compile-tests
run skydive-functional-tests-backend-elasticsearch

**Pull request merged**
