### PR TITLE
storage: switch to olivere/elastic elasticsearch library

### PR DESCRIPTION
**Pull request by lebauce**

### CODE REVIEW

**Comment by lebauce** [comment]
run skydive-functional-tests-backend-elasticsearch

**Comment by lebauce** [comment]
run tests

**Comment by lebauce** [comment]
run tests

**Comment by lebauce** [comment]
run skydive-functional-tests-backend-orientdb

**Comment by lebauce** [comment]
run  skydive-scale-tests

**Comment by lebauce** [comment]
run skydive-go-fmt

**Comment by lebauce** [comment]
run skydive-unit-tests

**Comment by lebauce** [comment]
run skydive-scale-tests

**Comment by lebauce** [comment]
run skydive-functional-tests-backend-elasticsearch

**Comment by lebauce** [comment]
run skydive-selenium-tests

**Comment by lebauce** [comment]
run skydive-selenium-tests

**Comment by lebauce** [comment]
run skydive-selenium-tests

**Comment by lebauce** [comment]
run run skydive-selenium-tests

**Comment by lebauce** [comment]
run skydive-selenium-tests

**Comment by lebauce** [comment]
run skydive-selenium-tests

**Comment by nplanel** [comment]
run skydive-functional-tests-backend-elasticsearch

**Comment by safchain** [comment]
rerun functional-tests-backend-elasticsearch

**Comment by safchain** [comment]
rerun functional-tests-backend-elasticsearch

**Comment by nplanel** [comment]
run skydive-scale-tests

**Comment by lebauce** [comment]
run skydive-selenium-tests

**Comment by nplanel** [comment]
run skydive-selenium-tests

**Comment by lebauce** [comment]
run run skydive-selenium-tests

**Comment by nplanel** [comment]
run skydive-selenium-tests

**Comment by nplanel** [comment]
run skydive-selenium-tests

**Comment by nplanel** [comment]
run skydive-functional-tests-backend-elasticsearch

**Comment by nplanel** [comment]
run skydive-scale-tests

**Comment by nplanel** [comment]
run run skydive-selenium-tests

**Comment by lebauce** [comment]
run skydive-functional-tests-backend-elasticsearch

**Comment by lebauce** [comment]
run  skydive-functional-tests-backend-orientdb

**Comment by lebauce** [comment]
run tests

**Comment by lebauce** [comment]
run skydive-functional-tests-backend-orientdb

**Comment by lebauce** [comment]
run skydive-selenium-tests

**Comment by nplanel** [comment]
run skydive-functional-tests-backend-orientdb

**Comment by nplanel** [comment]
run skydive-selenium-tests

**Comment by lebauce** [comment]
run skydive-functional-tests-backend-orientdb

**Comment by lebauce** [comment]
run skydive-selenium-tests

**Comment by lebauce** [comment]
run skydive-functional-tests-backend-orientdb

**Comment by lebauce** [comment]
run skydive-functional-tests-backend-orientdb

**Comment by nplanel** [comment]
run skydive-functional-tests-backend-elasticsearch

**Pull request merged**
