### PR TITLE
Analyzer probe cleanup

### PR DESCRIPTION
**Pull request by lebauce**

### CODE REVIEW

**Comment by lebauce** [comment]
run compile-tests
run cdd-overview-tests
run k8s-tests
run go-fmt
run unit-tests
run functional-tests-backend-elasticsearch
run scale-tests

**Comment by safchain** [comment]
run skydive-cdd-overview-tests
run skydive-k8s-tests

**Comment by lebauce** [comment]
run go-fmt
run unit-tests
run compile-tests
run functional-tests-backend-elasticsearch
run functional-tests-backend-orientdb
run k8s-tests

**Comment by lebauce** [comment]
run functional-tests-backend-elasticsearch

**Comment by lebauce** [comment]
run functional-tests-backend-elasticsearch

**Comment by lebauce** [comment]
run functional-tests-backend-elasticsearch

**Pull request merged**
