### PR TITLE
gopacket: back to master branch

### PR DESCRIPTION
**Pull request by safchain**

### CODE REVIEW

**Comment by safchain** [comment]
run skydive-functional-tests-backend-elasticsearch insanelock

**Comment by nplanel** [comment]
run skydive-unit-tests

**Comment by nplanel** [comment]
run skydive-unit-tests

**Comment by nplanel** [comment]
run skydive-unit-tests

**Comment by safchain** [comment]
run skydive-functional-tests-backend-elasticsearch

**Comment by safchain** [comment]
rerun tests

**Pull request merged**
