### PR TITLE
openflow: bug - probe creates zombies

### PR DESCRIPTION
**Pull request by pierrecregut**
Missing wait for execcommandpipe.

Closes: #1541

### CODE REVIEW

**Comment by safchain** [comment]
Thanks Pierre for addressing this

**Comment by mnasiadka** [comment]
Is that change part of any release? It would be nice to have it.

**Comment by lebauce** [comment]
@mnasiadka We are about to create a new release (in about a week I would say)

**Comment by mnasiadka** [comment]
@lebauce Any ETA for the release?

**Pull request merged**
