### PR TITLE
ansible & packaging fixes

### PR DESCRIPTION
**Pull request by safchain**

### CODE REVIEW

**Comment by safchain** [comment]
run skydive-tripleo-tests

**Comment by safchain** [comment]
rerun skydive-cdd-overview-tests

**Comment by safchain** [comment]
run skydive-tripleo-tests

**Comment by safchain** [comment]
run skydive-tripleo-tests

**Comment by lebauce** [comment]
run skydive-vagrant-tests

**Comment by safchain** [comment]
rerun skydive-functional-tests-backend-elasticsearch

**Comment by safchain** [comment]
rerun skydive-scale-tests

**Comment by safchain** [comment]
run skydive-packaging-tests

**Comment by safchain** [comment]
rerun skydive-cdd-overview-tests

**Comment by safchain** [comment]
rerun skydive-k8s-tests

**Comment by safchain** [comment]
rerun skydive-functional-tests-backend-orientdb

**Comment by safchain** [comment]
rerun skydive-functional-tests-backend-orientdb

**Comment by lebauce** [comment]
run skydive-vagrant-tests

**Comment by safchain** [comment]
run skydive-vagrant-tests

**Comment by safchain** [comment]
rerun skydive-cdd-overview-tests

**Comment by safchain** [comment]
rerun skydive-cdd-overview-tests

**Comment by nplanel** [comment]
run skydive-vagrant-tests

**Comment by safchain** [comment]
run skydive-vagrant-tests

**Comment by safchain** [comment]
run skydive-vagrant-tests

**Comment by safchain** [comment]
run skydive-vagrant-tests

**Comment by safchain** [comment]
run skydive-vagrant-tests

**Comment by safchain** [comment]
skydive-vagrant-tests

**Comment by safchain** [comment]
rerun skydive-vagrant-tests

**Pull request merged**
