### PR TITLE
CI : use linuxbridge as default for scale test

### PR DESCRIPTION
**Pull request by nplanel**

### CODE REVIEW

**Comment by nplanel** [comment]
run skydive-scale-tests

**Comment by nplanel** [comment]
run skydive-scale-tests

**Comment by nplanel** [comment]
run skydive-scale-tests

**Comment by nplanel** [comment]
run skydive-scale-tests

**Comment by nplanel** [comment]
http://ci.skydive.network:8080/job/skydive-scale-tests/760/consoleFull#footer  :  2nd flow B->A

**Comment by nplanel** [comment]
run skydive-scale-tests

**Comment by nplanel** [comment]
run skydive-scale-tests

**Comment by nplanel** [comment]
run skydive-scale-tests

**Comment by nplanel** [comment]
run skydive-scale-tests

**Comment by nplanel** [comment]
run skydive-scale-tests

**Comment by nplanel** [comment]
run skydive-scale-tests

**Comment by nplanel** [comment]
run skydive-scale-tests

**Comment by nplanel** [comment]
run skydive-scale-tests

**Comment by nplanel** [comment]
run skydive-scale-tests

**Comment by safchain** [comment]
run skydive-scale-tests

**Comment by safchain** [comment]
run scale-tests

**Comment by nplanel** [comment]
run skydive-scale-tests

**Comment by nplanel** [comment]
http://ci.skydive.network:8080/job/skydive-scale-tests/794/consoleFull#footer  drop 1st packet, as Transport:<Protocol:TCPPORT A:"5001" B:"53206"  should the reverse

**Comment by safchain** [comment]
run scale-tests

**Comment by nplanel** [comment]
run skydive-scale-tests

**Comment by nplanel** [comment]
run scale-tests

**Comment by nplanel** [comment]
http://ci.skydive.network:8080/job/skydive-scale-tests/806/consoleFull#footer  got 2 flow but one in reverse on agent-1 (iperf destination / server side)

**Comment by nplanel** [comment]
run scale-tests

**Comment by nplanel** [comment]
run scale-tests

**Comment by lebauce** [comment]
run scale-tests

**Comment by nplanel** [comment]
run skydive-scale-tests

**Comment by nplanel** [comment]
run scale-tests

**Comment by nplanel** [comment]
run scale-tests

**Comment by nplanel** [comment]
run scale-tests

**Comment by nplanel** [comment]
run scale-tests

**Comment by nplanel** [comment]
run scale-tests

**Comment by nplanel** [comment]
run scale-tests

**Comment by nplanel** [comment]
run scale-tests

**Comment by nplanel** [comment]
run skydive-scale-tests

**Comment by safchain** [comment]
Closing it as we don't have anymore issues, will re-open it if needed

**Pull request closed without merging**
