### PR TITLE
CI : run k8s functional tests only on baremetal

### PR DESCRIPTION
**Pull request by nplanel**

### CODE REVIEW

**Comment by nplanel** [comment]
run skydive-functional-tests-backend-elasticsearch

**Comment by hunchback** [comment]
@nplanel - why have we introduced this? I plan to use minikube on VirtualBox (devmode) and expect minikube/helm to install as part of running the functional test

**Comment by nplanel** [comment]
k8s cannot run on top of VM as they will generate nested VM (and crash the root/host VM) https://github.com/kubevirt/kubevirt/issues/940
I will fix that by pin special job on baremetal slaves

**Comment by lebauce** [comment]
run skydive-k8s-tests

**Comment by lebauce** [comment]
run skydive-k8s-tests

**Comment by lebauce** [comment]
run skydive-functional-tests-backend-elasticsearch

**Comment by lebauce** [comment]
run skydive-vagrant-tests

**Comment by lebauce** [comment]
run skydive-create-vagrant-boxes

**Comment by lebauce** [comment]
run skydive-devstack-tests

**Comment by lebauce** [comment]
run skydive-kolla-tests

**Comment by lebauce** [comment]
run skydive-kolla-tests

**Comment by lebauce** [comment]
run skydive-vagrant-tests

**Pull request merged**
