### PR TITLE
area: ui 

### PR DESCRIPTION
**Pull request by sergeyglazyrindev**
Hello guys
Here is an updated gui for skydive
Few things, mostly minor need to be fixed and I hope to finalize these things on this week.
you may start review this changeset and in the end of week I'll ask you to start using this new gui
There's a safe way to try out this ui. Just add to the query string: use_hardcoded_data=1&newui_approach=1

An example: http://192.168.56.101:8082/topology?use_hardcoded_data=1&newui_approach=1
If you want to try it out on fresh topology, remove use_hardcoded_data=1 from query string

skip skydive-go-fmt
skip skydive-functional-tests-backend-elasticsearch
skip skydive-functional-tests-backend-orientdb
skip skydive-scale-tests
skip skydive-unit-tests
skip skydive-compile-tests
skip skydive-k8s-tests
skip skydive-ppc64le-tests

### CODE REVIEW

**Comment by safchain** [comment]
@sergeyglazyrindev Thanks for submitting this, Indeed that is a huge PR :) Few first remarks about the approach and not the implementation. 

We should remove the generated files from the commit (JS) using the makefile to generate them. We don't need to have them in the repo and will ease the review process.

I worked on a patch to generate the REST API using Webpack/TS. I'll submit a draft by tomorrow so that we could use the same build process. 

The REST API generated and published here should be used https://www.npmjs.com/search?q=skydive I also converted the Websocket API using "real" class for nodes and edges. Everything compiles using strict option.

We need also to have the functional test passing "cdd_overview"

**Comment by sergeyglazyrindev** [comment]
@safchain , I'll update make file when fix all issues and remove generated file

**Comment by sergeyglazyrindev** [comment]
The remaining things are:
1. introduce a new layout which will be used for filtering the infrastructure topology using gremlin queries, etc
2. introduce one websocket per layout, get rid of global websocket handler
3. fix realtime updates in data structures
4. test link labels bandwidth for links, latencies, etc
5. test onNodeAdded and onEdgeAdded events and make sure emphasize handler works properly
6. test highlight and unhighlight events
7. fix all remaining @todo in the code (not so much)
8. do final tests

**Comment by sergeyglazyrindev** [comment]
Btw, do we have a typescript linter in our build process ? @lebauce , I think that makes sense to introduce such thing into our build process.

**Comment by sergeyglazyrindev** [comment]
> Btw, do we have a typescript linter in our build process ? @lebauce , I think that makes sense to introduce such thing into our build process.

I can do that but later.....

**Comment by safchain** [comment]
@safchain I working on adding typescript/webpack build in the build process so I can add the linter thing

**Comment by sergeyglazyrindev** [comment]
hello guys.
so the remaining things are:
1. fix typescript linter warnings
2. do final tests
3. integrate process of building topology package into makefile.
4. make sure all checks passed.

I think the changeset is ready for testing.
Unfortunately, I had to remove old way of building graph because usage of this global object: topologyComponent and graph made almost impossible to do a step by step integration of new approach.

How do we test it ? I made enough tests to make sure it works but I've not tested workflows, rule-detail component, there are some communication with graph/topologyComponent.

Tomorrow I'll fix typescript linter warnings.

**Comment by sergeyglazyrindev** [comment]
for sure there things which could be improved but right now I want to make a smooth transition from old approach to a new one. and then we can improve, write tests, actually, right now there's no tests for new approach because this stuff I developed from scratch during last two weeks. but we have one another stuff which has tests, etc: hierarchied topology
we may contribute it but only after this new approach would be merged because support of different layouts in skydive now very problematic.

**Comment by sergeyglazyrindev** [comment]
run skydive-cdd-overview-tests

**Comment by sergeyglazyrindev** [comment]
run skydive-ppc64le-tests

**Comment by sergeyglazyrindev** [comment]
run skydive-cdd-overview-tests

**Comment by sergeyglazyrindev** [comment]
run all

**Comment by sergeyglazyrindev** [comment]
run skydive-cdd-overview-tests

**Comment by sergeyglazyrindev** [comment]
run skydive-cdd-overview-tests

**Comment by sergeyglazyrindev** [comment]
run skydive-cdd-overview-tests

**Comment by sergeyglazyrindev** [comment]
run skydive-cdd-overview-tests

**Comment by sergeyglazyrindev** [comment]
skydive-cdd-overview-tests

**Comment by sergeyglazyrindev** [comment]
run skydive-cdd-overview-tests

**Comment by sergeyglazyrindev** [comment]
run skydive-cdd-overview-tests

**Comment by sergeyglazyrindev** [comment]
run skydive-cdd-overview-tests

**Comment by sergeyglazyrindev** [comment]
hello @lebauce 
Could you please send me a video from this test ?
http://ci-logs.skydive.network/skydive-cdd-overview-tests/builds/1141/log.html

**Comment by sergeyglazyrindev** [comment]
I fixed almost all tests but there's an issue which I am not able to troubleshoot even using javascript console.error in the code and then reading these messages in go code.

**Comment by safchain** [comment]
Hi @sergeyglazyrindev here the link for the video
http://ci-logs.skydive.network/skydive-cdd-overview-tests/builds/1141/archive/src/github.com/skydive-project/skydive/tests/

A part from that it may be a bit early to merge it as it is into the master branch. I would prefer to keep the "old" version of the WebUI adding the ability to add more layout instead of changing directly the currently behavior. Moreover we need to ask our UX to make a review in order to fix/improve some changes you introduced. As the effort you did is really needed and appreciated, I think it would be better to merge it into an dedicated branch, iterating to apply the required changes (UI/Design) then merge everything to the master branch. What do you think ?

**Comment by sergeyglazyrindev** [comment]
Hello @lebauce 
All tests fixed. And I believe now everything should work.
About your proposal. This is safest option but please keep in mind that right now if we decide to add more layouts to current approach it would not easy to migrate them later to new UI approach. Right now the code is not expandable well. I believe everything should wok now. And only minor issues are possible. So, for now there's only one remaining thing: fix typescript lint issues and redesign a little bit code because right now I don't like file structure in typescript. I wanted to do it at last. Let me know what you will do with this changeset and if you decide to merge to master I'll complete this last step: fix typescript linter issues, integrate process of building package into make process, and optimize/refactor a little bit typescript code as I am not happy about it.

**Comment by sergeyglazyrindev** [comment]
@lebauce that's why I vote for doing huge tests for this changeset and then adding layouts would be very easy. Right now to add layouts you will need to implement a lot of solutions similar to hacks.

**Comment by sergeyglazyrindev** [comment]
Hm,tests passed few times and now it doesn't work. But I am not able to see log file.

**Comment by safchain** [comment]
run skydive-cdd-overview-tests

**Comment by sergeyglazyrindev** [comment]
Btw,anyway now I switch to sriov contribution....

**Comment by sergeyglazyrindev** [comment]
okay, now all tests fixed.
The remaining things are: 
1. fix typescript linter issues
2. integrate process of building package into make process
3. optimize/refactor a little bit typescript code.

**Comment by sergeyglazyrindev** [comment]
if you want to merge it into another branch, it's ok for me. Do I need to do new pull request ?

**Comment by sergeyglazyrindev** [comment]
And yes we need to test it carefully. I've not tested well applying realtime changes to the topology. It's implemented but i am not sure if it works properly.

**Comment by safchain** [comment]
@sergeyglazyrindev sorry for the delay. No need to send a new PR I'll take all your commits and I will push them to another branch. Then I'll probably push commits on top of them to integrate some modifications according to the UX recommendation, etc. I propose to use this new branch as WIP branch so that we can work on it all together, comment, improve, etc.

I'll add you as reviewer for the UI PR.

**Comment by sergeyglazyrindev** [comment]
hi @lebauce 
But please keep in mind that it gives us a huge opportunity to expand areas of skydive usage and make it easier to integrate different layouts. So, I'd like to merge it asap to master to avoid huge javascript conflicts, etc. Let me know if you find any issues. I'll try to fix it asap.

**Comment by sergeyglazyrindev** [comment]
run skydive-cdd-overview-tests

**Comment by sergeyglazyrindev** [comment]
run skydive-cdd-overview-tests

**Comment by safchain** [comment]
@sergeyglazyrindev I'll have another look. As it is a huge patch it will take me a bit of time to be comfortable with it :). So first I'll have an another look at the global approach.

**Comment by sergeyglazyrindev** [comment]
right now I added a solution to support both versions of UI. I think old one works ok, I changed nothing. Tests are working. The only one thing, I moved all files which are supposed to be deleted to file: old_topology_approach.js
Later on when we migrate to new approach fully, we can remove just this file....

**Pull request closed without merging**
