### PR TITLE
swagger: Add authentication definition

### PR DESCRIPTION
**Pull request by safchain**

### CODE REVIEW

**Comment by safchain** [comment]
run skydive-scale-tests

**Comment by lebauce** [comment]
run scale-tests

**Comment by safchain** [comment]
run skydive-scale-tests

**Comment by safchain** [comment]
run tests

**Comment by safchain** [comment]
run skydive-functional-tests-backend-orientdb

**Comment by safchain** [comment]
run skydive-scale-tests

**Comment by safchain** [comment]
run skydive-scale-tests

**Comment by safchain** [comment]
run skydive-scale-tests

**Comment by safchain** [comment]
run skydive-scale-tests

**Pull request merged**
