### PR TITLE
netns: add netnsid to interfaces

### PR DESCRIPTION
**Pull request by safchain**

### CODE REVIEW

**Comment by safchain** [comment]
rerun scale-tests

**Comment by safchain** [comment]
waiting for a PR in netlink to be merge

**Comment by safchain** [comment]
rerun scale-tests

**Comment by safchain** [comment]
rerun functional-tests-backend-orientdb

**Comment by lebauce** [comment]
On hold because we sometimes get netlink messages with nsid set at zero (kernel bug ?)

**Comment by lebauce** [comment]
Did you think about reporting the `netnsid` on the `netns` object itself too ? (`ip netns set toto 123`)

**Comment by lebauce** [comment]
Works nicely by the way. If we want to report the netnsid in a later PR, it's fine for me to merge it as it

**Comment by safchain** [comment]
I did that but it seems I didn't commit the file ;( I'll do it

**Comment by safchain** [comment]
Ok I remember why I didn't submitted it :) It is because the netnsid is relative to the NetNS you are. So we can't determine a unique netnsid for a netns. I think we can merge it as it is.

**Pull request merged**
