### PR TITLE
ci: minikube install fixes

### PR DESCRIPTION
**Pull request by hunchback**
The fix adds checks to fail the install operation in case download does not successful complete, additionally we now use `minikube start` option to setup the `~vagrant` user correctly (replacing a set of commands which was failing on Ubuntu).

To check run:

```
for i in install start status stop uninstall; do
        scripts/ci/install-minikube.sh $i
done
```

### CODE REVIEW

**Comment by hunchback** [comment]
Failed due to:

```
22:46:48.556 ERROR: Step ‘Publish JUnit test result report’ failed: No test report files were found. Configuration error?
```

**Comment by lebauce** [comment]
run tests

**Comment by lebauce** [comment]
@hunchback The "22:46:48.556 ERROR: Step ‘Publish JUnit test result report’ failed: No test report files were found. Configuration error?" is not the error.

The real error seems to be:
```
10:15:19.989 2018-02-21T11:15:19.923+0100	INFO	elasticsearch/client.go:145 (*ElasticSearchClient).start	dpdk3: ElasticSearchStorage started
10:15:20.022 2018-02-21T11:15:19.956+0100	ERROR	analyzer/probes.go:53 NewTopologyProbeBundleFromConfig	dpdk3: Failed to initialize K8S probe: Failed to load Kubernetes config: invalid configuration: no configuration has been provided
10:15:20.024 panic: Failed to load Kubernetes config: invalid configuration: no configuration has been provided
```

**Comment by lebauce** [comment]
@hunchback You probably need to run `minikube start` with `sudo -E`

**Comment by hunchback** [comment]
Have added `-E` flag as in `sudo -E $(which minikube) .... start`

**Comment by lebauce** [comment]
run tests

**Comment by lebauce** [comment]
Can you please rebase on master ?

**Pull request merged**
