### PR TITLE
ci: run scale tests with api and cluster authentications

### PR DESCRIPTION
**Pull request by lebauce**

### CODE REVIEW

**Comment by safchain** [comment]
run skydive-cdd-overview-tests

**Comment by safchain** [comment]
run skydive-cdd-overview-tests

**Comment by safchain** [comment]
run skydive-cdd-overview-tests

**Comment by safchain** [comment]
run skydive-cdd-overview-tests

**Comment by lebauce** [comment]
run skydive-cdd-overview-tests

**Comment by lebauce** [comment]
run skydive-ppc64le-tests

**Comment by lebauce** [comment]
run skydive-functional-tests-backend-elasticsearch

**Pull request merged**
