### PR TITLE
ui: add highlight circle instead of changing color for highlighted nodes

### PR DESCRIPTION
**Pull request by safchain**

### CODE REVIEW

**Comment by safchain** [comment]
run cdd-overview

**Comment by safchain** [comment]
run cdd-overview

**Comment by masco-enovance** [comment]
after moving out from flows the highlighted nodes are not coming back to normal. not reproducing for the first time just go and come out on the flows for two-three times after that the nodes remain highlighted.

**Comment by masco-enovance** [comment]
here is my screenshot https://pasteboard.co/GXGUvte.png

**Comment by safchain** [comment]
rerun selenium-tests

**Pull request merged**
