### PR TITLE
ui: fix flow-table sort

### LINKED ISSUE #804: Sort order for flow numeric columns weird
If you click the column label under the flow query table to sort the flows by that column, the sort order is a bit weird for numeric fields like AB/BA Packets/Bytes. It seems to treat the values like text instead of numbers, causing the order to be wrong.

For example:
1
1000
2
300

Instead of the natural
1
2
300
1000

### PR DESCRIPTION
**Pull request by eonpatapon**
Closes #804

### CODE REVIEW

**Comment by lebauce** [comment]
run skydive-functional-tests-backend-elasticsearch

**Comment by lebauce** [comment]
run skydive-scale-tests

**Comment by lebauce** [comment]
@eonpatapon Can you please rebase on master ? We recently fixed a bunch of CI fixes. Thanks !

**Comment by masco-enovance** [comment]
@eonpatapon conversation sort issue is fixed here https://github.com/skydive-project/skydive/pull/815

**Comment by eonpatapon** [comment]
Done!

Excerpts from Sylvain Baubeau's message of February 26, 2018 1:27 pm:

**Comment by masco-enovance** [comment]
run skydive-scale-tests

**Comment by masco-enovance** [comment]
Tested. working good. waiting for CI tests. Thanks!

**Comment by nplanel** [comment]
run tests

**Comment by eonpatapon** [comment]
Is there some ui tests now ?

**Pull request merged**
