### PR TITLE
tests: fix functional tests in static mode

### PR DESCRIPTION
**Pull request by lebauce**
skip skydive-go-fmt
skip skydive-functional-tests-backend-elasticsearch
skip skydive-functional-tests-backend-orientdb
skip skydive-scale-tests
skip skydive-cdd-overview-tests
skip skydive-unit-tests
skip skydive-compile-tests
skip skydive-k8s-tests
skip skydive-ppc64le-tests
skip skydive-functional-hw-tests

### CODE REVIEW

**Comment by lebauce** [comment]
run skydive-opencontrail-tests

**Comment by lebauce** [comment]
@nlewo It seems we are missing the `libnl` library. Where this dependency should be added ?

**Comment by nlewo** [comment]
@lebauce I think there: 
- https://github.com/skydive-project/skydive/blob/master/Makefile#L105
- https://github.com/skydive-project/skydive/blob/master/Makefile#L114
If this doesn't work, I could give a try on next week.

**Comment by lebauce** [comment]
@nlewo I thought that libnl had to be installed using NixOS but I don't know how to do this

**Comment by nlewo** [comment]
No, I don't think so. If I remember correctly, the binary is statically compiled on the Jenkins host, without relying on any Nix stuffs.

**Pull request closed without merging**
