### PR TITLE
ui: expand all childs in a group

### PR DESCRIPTION
**Pull request by masco-enovance**
added a dedicated button for node to expand
and collapse all the child groups in the node group.

### CODE REVIEW

**Comment by masco-enovance** [comment]
run tests

**Comment by masco-enovance** [comment]
run coverage

**Comment by nplanel** [comment]
run skydive-coverage

**Comment by masco-enovance** [comment]
run coverage

**Comment by vperelmax** [comment]
Looks, fine to me.
Small comment: I think the icon and its placement near "metadatas" is not intuitive...
Maybe, we should add button with name "Collapse/Expand" similar to general button. also it is better for each thing to have as unique way as possible in the UI.

**Comment by vperelmax** [comment]
By the way, the code is written very nice!
Another small note/suggestion: maybe we should add some way to give to user by maybe double click on "+" icon of the button to explicitly say how many levels we would like to open.
Just thinking aloud :)

**Comment by masco-enovance** [comment]
Added a button in topology window too. it will appear only after selecting any one node.

**Comment by safchain** [comment]
Maybe we should now use only images in the toolbar, it will take less place and will be more consistent but that another story! :)

**Pull request merged**
