### PR TITLE
K8s service probe

### PR DESCRIPTION
**Pull request by hunchback**
Add new service probe to test add following to skydive.yml

```
k8s:
  probes:
    service
```

### CODE REVIEW

**Comment by hunchback** [comment]
@lebauce - rebased

**Comment by safchain** [comment]
ok to test

**Comment by hunchback** [comment]
strangely I can't access the log of the failed tests at: http://ci-logs.skydive.network/skydive-unit-tests/builds/466/log.html

**Comment by lebauce** [comment]
run skydive-unit-tests

**Pull request merged**
