### PR TITLE
packaging: bump rpm version to 0.21.0

### PR DESCRIPTION
**Pull request by lebauce**
skip skydive-go-fmt
skip skydive-functional-tests-backend-elasticsearch
skip skydive-functional-tests-backend-orientdb
skip skydive-scale-tests
skip skydive-cdd-overview-tests
skip skydive-unit-tests
skip skydive-compile-tests
skip skydive-k8s-tests
skip skydive-ppc64le-tests

### CODE REVIEW

**Comment by lebauce** [comment]
run skydive-build-copr

**Comment by lebauce** [comment]
run skydive-create-docker-image

**Comment by nplanel** [comment]
run skydive-create-docker-image

**Comment by nplanel** [comment]
run skydive-create-docker-image

**Comment by nplanel** [comment]
merge this PR before the v0.21.0 tag https://github.com/skydive-project/skydive/pull/1503

**Pull request merged**
