### PR TITLE
neutron: reduce graph presure

### PR DESCRIPTION
**Pull request by safchain**

### CODE REVIEW

**Comment by safchain** [comment]
run devstack

**Comment by safchain** [comment]
run devstack-plugin

**Comment by safchain** [comment]
run devstack-plugin

**Comment by safchain** [comment]
run devstack

**Comment by safchain** [comment]
run devstack

**Comment by safchain** [comment]
run devstack

**Comment by matrohon** [comment]
👍 . It seems to have fixed crashes observed on agent during multiple captures.

**Comment by lebauce** [comment]
run selenium-tests

**Pull request merged**
