### PR TITLE
build: fix build of docker images

### PR DESCRIPTION
**Pull request by safchain**
skip skydive-functional-tests-backend-orientdb
skip skydive-go-fmt
skip skydive-k8s-tests
skip skydive-scale-tests
skip skydive-selenium-tests
skip skydive-unit-tests
skip skydive-cdd-overview-tests
skip skydive-ppc64-tests

### CODE REVIEW

**Comment by safchain** [comment]
run skydive-create-docker-image

**Comment by safchain** [comment]
run skydive-create-docker-image

**Comment by hunchback** [comment]
this worked fine for me ...:

```
+ docker build -t ibmcom/skydive:latest-linux-s390x --label Version=latest --build-arg ARCH=s390x --build-arg BASE=s390x/ubuntu -f contrib/docker/Dockerfile.static contrib/docker
Sending build context to Docker daemon  592.7MB
Step 1/7 : ARG  BASE=ubuntu:18.04
Step 2/7 : FROM $BASE
 ---> 9fae3560b76f
Step 3/7 : ARG  ARCH=x86_64
 ---> Using cache
 ---> ff1b108b1ee3
Step 4/7 : COPY skydive.$ARCH /usr/bin/skydive
 ---> a4377889dda8
Step 5/7 : COPY skydive.yml /etc/skydive.yml
 ---> 190254fe32b8
Step 6/7 : ENTRYPOINT ["/usr/bin/skydive", "--conf", "/etc/skydive.yml"]
 ---> Running in a47cedc97ae5
Removing intermediate container a47cedc97ae5
 ---> 289c8692fb2f
Step 7/7 : LABEL Version=latest
 ---> Running in 70f3990d1260
Removing intermediate container 70f3990d1260
 ---> 199e767580ff
Successfully built 199e767580ff
Successfully tagged ibmcom/skydive:latest-linux-s390x
+ [ latest == latest ]
scripts/ci/create-docker-image.sh: 95: [: latest: unexpected operator

if [ -n "$DRY_RUN" ]; then
    echo "Running in dry run mode. Exiting."
    exit 0
fi
+ [ -n 1 ]
+ echo Running in dry run mode. Exiting.
Running in dry run mode. Exiting.
+ exit 0
root@iris-nvt:~/community/go/src/github.com/skydive-project/skydive#
```

**Comment by safchain** [comment]
run skydive-create-docker-image

**Comment by safchain** [comment]
run skydive-create-docker-image

**Comment by safchain** [comment]
run skydive-functional-hw-tests
run skydive-functional-tests-backend-elasticsearch

**Comment by safchain** [comment]
run skydive-create-docker-image

**Comment by safchain** [comment]
run skydive-create-docker-image

**Comment by safchain** [comment]
run skydive-create-docker-image

**Comment by safchain** [comment]
run skydive-functional-tests-backend-elasticsearch

**Comment by safchain** [comment]
run skydive-create-docker-image

**Comment by safchain** [comment]
run skydive-functional-tests-backend-elasticsearch

**Pull request merged**
