### PR TITLE
ui,oflow: group openflow rules by priority and actions

### LINKED ISSUE #970: Group Openflow rules by priority and actions
Long lists of rules can be hard to read. A first step would be to group them by priority and for a given priority by actions. Rules of a given subgroup would only be distinguishable by the filters (it should be read as a disjunction). 

Here is a table taken from an vswitch controlled by openstack/ovn with the current style: 
old_layout

Here is the same with the new slightly more structured style:
new-layout

### PR DESCRIPTION
**Pull request by pierrecregut**
* Make priority of the rule a separated column.
* Rules of same priority share a single priority cell spanning multiple
  rows.
* Rules with the same set of actions share a single cell spanning
  multiple rows (They have different filters).

Closes #970

### CODE REVIEW

**Comment by pierrecregut** [comment]
run tests

**Comment by masco-enovance** [comment]
run tests

**Comment by masco-enovance** [comment]
ok to test

**Comment by nplanel** [comment]
run skydive-selenium-tests

**Pull request merged**
