### PR TITLE
etcd: fix initial cluster detection

### PR DESCRIPTION
**Pull request by lebauce**

### CODE REVIEW

**Comment by lebauce** [comment]
run tests

**Comment by hunchback** [comment]
After checking the PR we still get the errors:

**2018-02-22 16:03:44.457723 I | etcdserver/membership: added member ddd67b312462fd7b [http://127.0.0.1:12380] to cluster a7ef944b95711739**

```
2018-02-22 16:03:44.335773 I | etcdserver: advertise client URLs = http://127.0.0.1:2379,http://10.0.2.15:2379,http://[::1]:2379
2018-02-22 16:03:44.437677 I | etcdserver: restarting member ddd67b312462fd7b in cluster a7ef944b95711739 at commit index 41437
2018-02-22 16:03:44.440159 I | raft: ddd67b312462fd7b became follower at term 39
2018-02-22 16:03:44.440184 I | raft: newRaft ddd67b312462fd7b [peers: [], term: 39, commit: 41437, applied: 0, lastindex: 41437, lastterm: 39]
2018-02-22 16:03:44.451428 W | auth: simple token is not cryptographically signed
2018-02-22 16:03:44.454139 I | etcdserver: starting server... [version: 3.2.15+git, cluster version: to_be_decided]
2018-02-22 16:03:44.457723 I | etcdserver/membership: added member ddd67b312462fd7b [http://127.0.0.1:12380] to cluster a7ef944b95711739
2018-02-22 16:03:44.457841 N | etcdserver/membership: set the initial cluster version to 3.2
2018-02-22 16:03:44.457875 I | etcdserver/api: enabled capabilities for version 3.2
2018-02-22 16:03:44.840929 I | raft: ddd67b312462fd7b is starting a new election 
```

**Comment by lebauce** [comment]
@hunchback I don't see any error in the output you posted :-/ The problem @eranra had was:
```
Failed to create analyzer: --initial-cluster must include bd9fcabbd695=http://127.0.0.1:2380,bd9fcabbd695=http://172.17.0.22:2380 given --initial-advertise-peer-urls=http://127.0.0.1:2380,http://172.17.0.22:2380/
```

**Comment by lebauce** [comment]
run skydive-functional-tests-backend-elasticsearch

**Comment by hunchback** [comment]
@lebauce - but still I don't understand why our peer port is 12380 after we define `etcd.listen = :2379` ... may expectation was that the peer port would be 2380 (2379+1).

**Comment by lebauce** [comment]
@hunchback This is due to the cache. You need to remove the old data dir for etcd.

**Comment by hunchback** [comment]
Ok, then i am fine with the fix

**Pull request merged**
