### PR TITLE
Fix scale tests

### PR DESCRIPTION
**Pull request by lebauce**

### CODE REVIEW

**Comment by lebauce** [comment]
run skydive-scale-tests

**Comment by nplanel** [comment]
run skydive-scale-tests

**Comment by lebauce** [comment]
run skydive-scale-tests

**Comment by lebauce** [comment]
run skydive-functional-tests-backend-elasticsearch

**Comment by lebauce** [comment]
run skydive-functional-tests-backend-elasticsearch

**Comment by lebauce** [comment]
run skydive-functional-tests-backend-elasticsearch

**Comment by lebauce** [comment]
run skydive-functional-tests-backend-orientdb

**Comment by lebauce** [comment]
run skydive-functional-tests-backend-orientdb

**Comment by lebauce** [comment]
run tests

**Comment by lebauce** [comment]
run tests

**Comment by lebauce** [comment]
run skydive-coverage

**Comment by lebauce** [comment]
run skydive-packaging-tests

**Comment by lebauce** [comment]
run skydive-python-tests

**Comment by lebauce** [comment]
run skydive-coverage

**Pull request merged**
