### PR TITLE
release: bump to 0.20.0

### PR DESCRIPTION
**Pull request by lebauce**

### CODE REVIEW

**Comment by lebauce** [comment]
run skydive-packaging-tests

**Comment by lebauce** [comment]
run skydive-python-tests

**Comment by safchain** [comment]
run skydive-python-tests

**Comment by lebauce** [comment]
run skydive-create-docker-images

**Comment by lebauce** [comment]
run skydive-python-tests

**Comment by lebauce** [comment]
run skydive-functional-tests-backend-elasticsearch

**Pull request merged**
