### PR TITLE
Startup cleanup

### PR DESCRIPTION
**Pull request by lebauce**

### CODE REVIEW

**Comment by lebauce** [comment]
run scale-tests

**Comment by lebauce** [comment]
run skydive-functional-tests-backend-orientdb

**Comment by lebauce** [comment]
run skydive-functional-tests-backend-orientdb

**Comment by lebauce** [comment]
run tests

**Comment by lebauce** [comment]
run skydive-functional-tests-backend-orientdb

**Comment by safchain** [comment]
rerun skydive-unit-tests

**Pull request merged**
