### PR TITLE
Add PATCH method to modify resources

### PR DESCRIPTION
**Pull request by adrianlzt**
Allow a new call to the REST API, using method PATCH, to modify
resources.
The body of the request should use JSON Patch
(https://tools.ietf.org/html/rfc6902) to specify the modifications.

Only metatada could be modified.
For node resources, some fields inside metadata could not be changed.

### CODE REVIEW

**Comment by lebauce** [comment]
run k8s-tests

**Comment by lebauce** [comment]
run k8s-tests

**Comment by lebauce** [comment]
run k8s-tests

**Comment by lebauce** [comment]
run functional-tests-backend-elasticsearch

**Comment by adrianlzt** [comment]
:)

**Comment by adrianlzt** [comment]
@safchain could you release a new version of the python lib? thanks!

**Comment by adrianlzt** [comment]
@safchain new pypi? :)

**Pull request merged**
