### PR TITLE
CI : remove vpp-plugins as it's not used

### PR DESCRIPTION
**Pull request by nplanel**

### CODE REVIEW

**Comment by lebauce** [comment]
run skydive-cdd-overview-tests
run skydive-functional-hw-tests
run skydive-functional-tests-backend-elasticsearch
run skydive-functional-tests-backend-orientdb
run skydive-k8s-tests

**Comment by nplanel** [comment]
run skydive-functional-hw-tests

**Comment by nplanel** [comment]
run skydive-k8s-tests

**Comment by safchain** [comment]
run skydive-functional-hw-tests

**Comment by nplanel** [comment]
run skydive-functional-hw-tests

**Comment by nplanel** [comment]
run skydive-functional-hw-tests

**Pull request merged**
