### PR TITLE
tests: fix vpp functional tests

### PR DESCRIPTION
**Pull request by nplanel**

### CODE REVIEW

**Comment by lebauce** [comment]
:+1:

**Comment by pierrecregut** [comment]
Note that it fixes the compilation bug, but the test is not run.

**Comment by pierrecregut** [comment]
rename vpp_tests.go in vpp_test.go

**Comment by lebauce** [comment]
run skydive-k8s-tests

**Comment by lebauce** [comment]
run skydive-functional-tests-backend-orientdb

**Comment by lebauce** [comment]
run skydive-cdd-overview-tests

**Comment by lebauce** [comment]
run skydive-functional-tests-backend-orientdb

**Comment by nplanel** [comment]
run skydive-functional-hw-tests

**Comment by nplanel** [comment]
run skydive-functional-hw-tests

**Comment by nplanel** [comment]
run skydive-functional-hw-tests

**Comment by pierrecregut** [comment]
I think a previous comment was buried. I do not believe that skydive and the system can safely converge in only 200ms. I would try something like:
```go
err := common.Retry(
    func() error {
        gremlin = c.gremlin.V().Has("Driver", "vpp", "Name", loop2)
        if nodes, err = c.gh.GetNodes(gremlin); err != nil {
            return err
        }
        if len(nodes) < 1 {
            return fmt.Errorf("Expected one interface, got %+v", nodes)
        }
    },
    YourPreferedRetryValue, time.Second)
if err != nil {
    return err
}
```

**Comment by nplanel** [comment]
run skydive-functional-hw-tests

**Comment by nplanel** [comment]
run skydive-functional-hw-tests

**Comment by nplanel** [comment]
run skydive-functional-hw-tests

**Comment by nplanel** [comment]
run skydive-functional-hw-tests

**Comment by nplanel** [comment]
run skydive-functional-hw-tests

**Comment by nplanel** [comment]
run skydive-functional-hw-tests

**Comment by nplanel** [comment]
run skydive-functional-hw-tests

**Comment by nplanel** [comment]
depending on this govpp fix upstream : https://gerrit.fd.io/r/#/c/18423/

**Comment by nplanel** [comment]
run tests

**Comment by nplanel** [comment]
run skydive-functional-tests-backend-orientdb

**Comment by nplanel** [comment]
run skydive-opencontrail-tests

**Comment by lebauce** [comment]
run skydive-cdd-overview-tests

**Comment by lebauce** [comment]
run skydive-functional-tests-backend-orientdb

**Pull request merged**
