### PR TITLE
Netlink perm hwaddr

### PR DESCRIPTION
**Pull request by lebauce**

### CODE REVIEW

**Comment by lebauce** [comment]
run skydive-cdd-overview-tests

**Comment by lebauce** [comment]
run skydive-functional-tests-backend-orientdb

**Comment by lebauce** [comment]
run skydive-k8s-tests

**Comment by lebauce** [comment]
run skydive-k8s-tests

**Comment by jrosser** [comment]
I see the extra data present in the topology json but the "extra" switch nodes are not pruned from the UI currently.

**Comment by lebauce** [comment]
@jrosser I'm trying to reproduce it on my setup. Could you please send an other topology dump ? Thanks !

**Pull request closed without merging**
