### PR TITLE
fix gopkg.in/fsnotify/fsnotify.v1 new package path

### PR DESCRIPTION
**Pull request by nplanel**

### CODE REVIEW

**Comment by safchain** [comment]
rerun tests

**Comment by nplanel** [comment]
run skydive-go-fmt

**Comment by safchain** [comment]
rerun tests

**Comment by safchain** [comment]
rerun tests

**Comment by safchain** [comment]
rerun tests

**Comment by safchain** [comment]
rerun tests

**Comment by safchain** [comment]
rerun tests

**Pull request merged**
