### PR TITLE
devstack: move the config to etc and make a symlink of the binary to …

### PR DESCRIPTION
**Pull request by safchain**
…/usr/bin

skip skydive-go-fmt
skip skydive-functional-tests-backend-elasticsearch
skip skydive-functional-tests-backend-orientdb
skip skydive-scale-tests
skip skydive-cdd-overview-tests
skip skydive-unit-tests
skip skydive-compile-tests
skip skydive-k8s-tests
skip skydive-ppc64le-tests

### CODE REVIEW

**Comment by safchain** [comment]
run devstack-tests

**Comment by nplanel** [comment]
:+1:

**Comment by safchain** [comment]
rerun skydive-functional-tests-backend-elasticsearch

**Comment by safchain** [comment]
rerun skydive-k8s-tests

**Comment by safchain** [comment]
rerun skydive-k8s-tests

**Comment by lebauce** [comment]
run devstack-tests

**Comment by lebauce** [comment]
run devstack-tests

**Pull request merged**
