### PR TITLE
release: bump to 0.21.0

### PR DESCRIPTION
**Pull request by lebauce**

### CODE REVIEW

**Comment by lebauce** [comment]
run skydive-functional-tests-backend-elasticsearch

**Comment by lebauce** [comment]
run skydive-functional-tests-backend-orientdb

**Comment by lebauce** [comment]
run skydive-packaging-tests

**Comment by nplanel** [comment]
:+1:

**Comment by nplanel** [comment]
run python-tests

**Comment by nplanel** [comment]
run skydive-ppc64le-tests

**Pull request merged**
