### PR TITLE
graph: fixed major bug in GetFirstLink()

### PR DESCRIPTION
**Pull request by hunchback**
Need to verify all tests still pass

### CODE REVIEW

**Comment by safchain** [comment]
run skydive-functional-tests-backend-elasticsearch

**Comment by nplanel** [comment]
@hunchback could you please add an unit tests that test/show this bug in topology/graph/graph_test.go

**Comment by nplanel** [comment]
run skydive-functional-tests-backend-orientdb

**Comment by hunchback** [comment]
Yes, i will add a test

**Comment by hunchback** [comment]
run skydive-cdd-overview-tests

**Comment by hunchback** [comment]
@safchain / @nplanel - any insights (before I drill down) on why these tests are failing?

**Comment by safchain** [comment]
run skydive-functional-tests-backend-elasticsearch

**Comment by safchain** [comment]
@hunchback checking, for the cdd one, seems like docker was stopped on the machines

**Comment by safchain** [comment]
run skydive-functional-tests-backend-orientdb

**Comment by safchain** [comment]
run skydive-cdd-overview-tests

**Comment by hunchback** [comment]
run skydive-functional-tests-backend-orientdb

**Comment by nplanel** [comment]
run skydive-functional-tests-backend-orientdb

**Comment by nplanel** [comment]
run skydive-functional-tests-backend-orientdb

**Comment by nplanel** [comment]
run skydive-functional-tests-backend-orientdb

**Comment by nplanel** [comment]
run skydive-functional-tests-backend-orientdb

**Comment by hunchback** [comment]
Are we any closer in understanding why `skydive-functional-tests-backend-orientdb` is repeatedly failing?

**Comment by nplanel** [comment]
run skydive-functional-tests-backend-orientdb

**Comment by nplanel** [comment]
@hunchback test was failing because some CI slaves didn't have docker running due to rdo maintenance reboot

**Pull request merged**
