### PR TITLE
neutron: give a chance to find port on slow environment

### PR DESCRIPTION
**Pull request by safchain**

### CODE REVIEW

**Comment by lebauce** [comment]
nit: replace ',' by ':' in the commit message

**Comment by safchain** [comment]
rerun selenium-tests

**Comment by safchain** [comment]
run devstack

**Comment by safchain** [comment]
run devstack

**Comment by safchain** [comment]
run devstack

**Comment by safchain** [comment]
run devstack

**Comment by safchain** [comment]
Will try to find a better approach

**Pull request closed without merging**
