### PR TITLE
k8s/test: add wordpress sample

### PR DESCRIPTION
**Pull request by hunchback**
added a new k8s sample and test scenario - wordpress backed by mysql and pvc

you can check the PR by:

Open the WebUI and run:

```
tests/k8s/wordpress.sh start
# verify wordress-mysql and wordpress deployments were created

tests/k8s/wordpress.sh status
# connect a Web to the service port to view wordpress execution

tests/k8s/wordpress.sh stop
# verify wordpress resources are removed
```

### CODE REVIEW

**Comment by safchain** [comment]
need to be rebased

**Comment by hunchback** [comment]
run skydive-functional-tests-backend-orientdb

**Comment by hunchback** [comment]
run skydive-functional-tests-backend-elasticsearch

**Comment by hunchback** [comment]
run skydive-functional-hw-tests

**Comment by hunchback** [comment]
run skydive-functional-hw-tests

**Comment by lebauce** [comment]
@hunchback Can you please rebase this PR ?

**Comment by hunchback** [comment]
run skydive-k8s-tests

**Pull request merged**
