### PR TITLE
Add support for gremlin union (or) step

### PR DESCRIPTION
**Pull request by rkhachatryan**
Hello,
I'd like to provide an implementation of UNION/OR step as was proposed in #426  (see [docs](http://gremlindocs.spmallette.documentup.com/#or) )

I think explicit OR step will give more abilities than existing/upcoming steps, for example to combine results of different steps: `G.V().Or(Has('Value', 2).In(), Has('Value', 3).Out())`
Also using explicit OR may be more convenient.
Further NOT and AND steps can be implemented based on this changes.

Overview of changes
1. added new step, it's scanning and execution
1. added new method to scan for nested steps in parentheses
1. changed parsing to parse nested steps
1. added unit tests, changed existing - extracted some common code

(tried to keep changes minimal to not affect existing functionality)

NOTES: 
1. added scan method is able to scan strings with arbitrary depth and also deals with escaping
1. infix notation not implemented
1. underscore in not needed and not interpreted in the beginning of nested sequences

### CODE REVIEW

**Comment by safchain** [comment]
ok to test

**Comment by safchain** [comment]
@rkhachatryan Thx for submitting this :) we will have a deep look at it. Meanwhile I'm adding you to the whitelist for the CI so that if you push updates, jobs will be triggered automatically.

**Comment by safchain** [comment]
add to whitelist

**Comment by rkhachatryan** [comment]
run skydive-functional-tests-backend-orientdb

**Comment by safchain** [comment]
run skydive-functional-tests-backend-orientdb

**Comment by eonpatapon** [comment]
I think this step name should be just or(), not union().

If you look at the gremlin (tinkerpop) doc union() is a branching step that yieds multiple traversals whereas or() is a filter step for the current traversal

**Comment by safchain** [comment]
run skydive-functional-tests-backend-orientdb

**Comment by rkhachatryan** [comment]
Thanks for reviewing!

You are right, I didn't make difference between these two steps. And currently this PR implements UNION rather than OR.

Implementing OR will require keeping track of which elements produce which elements when executing the each step.

So now I see the following options:
1. Keep track of which graphElement from initialStep has outputs and which hasn't. To do this we'll need to modify each Gremlin Step because they transform one set of elements to another. This will require a lot of changes.
1. For each graphElement from initial step create a fake step and Exec GremlinTraversalSequence to determine whether it has outputs or not. This may cause problems in queries like g.V().or(_().V(2))
1. Just rename current step to Union

I propose just to change the name to union (and remove OR token).

**Comment by safchain** [comment]
Yes keeping the union behavior sounds good. Could you just convert the WrapperGraphTraversalStep to something like GraphTraversalSet which could be

type GraphTraversalSet struct {
  vs []GraphTraversalV
  es []GraphTraversalE
  err error
}

so that we fill this structure with the results of the union. We could add "sub" steps for this step later like subgraph ?

**Comment by rkhachatryan** [comment]
When we build this struct we only have a collection of GraphTraversalStep as a result of executing GremlinTraversalSequence s. 

That can be not only GraphTraversalE/V but also GraphTraversalShortestPath or something else.

If the next step needs to differentiate these types then why not to do it there in step.Exec method?

**Comment by safchain** [comment]
Right for the collection of GraphTraversalStep. Your approach looks good to me.

**Comment by safchain** [comment]
@rkhachatryan do you have any news on this ?

**Comment by rkhachatryan** [comment]
@safchain, right now I don't have time to work on this, maybe on weekend.

**Comment by safchain** [comment]
@rkhachatryan no problem :)

**Comment by safchain** [comment]
@rkhachatryan Hi, did/do you have time to work on this ? can we help you maybe in order to have it merge as it is a nice feature ?

**Comment by safchain** [comment]
Closing it for now since as/select steps have been introduced handling the use cases

**Pull request closed without merging**
