### PR TITLE
coverage: fix wrong tags parameter

### PR DESCRIPTION
**Pull request by lebauce**

### CODE REVIEW

**Comment by lebauce** [comment]
run skydive-coverage

**Comment by lebauce** [comment]
run skydive-scale-tests

**Comment by lebauce** [comment]
run tests

**Comment by lebauce** [comment]
run skydive-scale-tests

**Comment by lebauce** [comment]
run skydive-scale-tests

**Comment by lebauce** [comment]
run skydive-scale-tests

**Comment by nplanel** [comment]
run skydive-coverage

**Comment by lebauce** [comment]
run skydive-scale-tests

**Comment by lebauce** [comment]
Merged with https://github.com/skydive-project/skydive/pull/802

**Pull request closed without merging**
