### PR TITLE
Converted HELM chart to a operator using operator-sdk

### PR DESCRIPTION
**Pull request by lebauce**

### CODE REVIEW

**Comment by hunchback** [comment]
run skydive-compile-tests

**Comment by hunchback** [comment]
what version of operator-sdk was used?

how can the operator be tested?

**Comment by hunchback** [comment]
@alericks21 - thanks a lot for - some questions came up:
- what was the base helm chart you used for the conversion?
- how did you test the operator is working?
- what is the command like used for generating the operator (using the operator-sdk)

**Comment by lebauce** [comment]
Now in https://github.com/skydive-project/skydive-operator

**Pull request closed without merging**
