### PR TITLE
Storage rolling elastic

### PR DESCRIPTION
**Pull request by eranra**

### CODE REVIEW

**Comment by safchain** [comment]
ok to test

**Comment by safchain** [comment]
rerun tests

**Comment by safchain** [comment]
rerun tests

**Comment by eranra** [comment]
rerun skydive-compile-tests

**Comment by eranra** [comment]
Hi Sylvain, can you rerun tests ... THX

**Comment by eranra** [comment]
I did a test with a single agent connecting and disconnecting several times and writing the expected results:
```
12:43 no agent
12:44 no agent
12:45 start agent
12:46 agent exists
12:47 stop agent
12:48 start agent
12:49 agent exists
12:50 agent exists - roll (12:50:25)
12:51 agent exists
12:52 stop agent
```

**Comment by eranra** [comment]
I also ran the bellow to get number of records with 'ArchivedAt' flag and we have 102 in the archived log == all records, as expected
```
$ curl -XGET 'http://localhost:9200/skydive_topology_v11_2018-04-12_00-43-47/_count?q=_exists_:ArchivedAt' {"count":102,"_shards":{"total":5,"successful":5,"failed":0}}
```

Now, when the agent is down, when checking the latest index (that should include 'live' and archive) I get 38 records out of 42 are archived, exactly as expected:

```
$ curl -XGET 'http://localhost:9200/skydive_topology_v11_2018-04-12_00-50-25/_count?q=_exists_:ArchivedAt'
{"count":38,"_shards":{"total":5,"successful":5,"failed":0}}
```

**Comment by eranra** [comment]
**From my point of view, all manual tests passed so we can go ahead and merge.**

Next phase (next PR) will be to fix the age challenge, in the current version is is commented out with big TODO mark ...  there are two options to solve this challenge.  We can use the index name (that includes the date it was created) or insert special record with createdAt value when creating the index, and read it when opening.

**Comment by safchain** [comment]
@eranra thanks for all the tests. We had CI issue since yesterday, going to restart tests

**Comment by safchain** [comment]
ok to tests

**Comment by safchain** [comment]
rerun tests

**Comment by eranra** [comment]
Still something is strange ... I see in the log
```
--- PASS: TestRouteTableHistory (16.27s)
	tests.go:251: Removing existing captures
	tests.go:259: Creating captures
	tests.go:271: Executing setup commands
	tests.go:281: Checking captures are correctly set up
	tests.go:327: Executing settle function
	tests.go:345: Executing setup function
	tests.go:456: Running checks
	tests.go:485: Running tear down commands
FAIL
``` 
And "skydive-functional-tests-backend-elasticsearch " hanges.
Maybe the CI is still not working as expected ?

**Comment by safchain** [comment]
rerun unit-tests

**Comment by safchain** [comment]
rerun selenium-tests

**Comment by safchain** [comment]
rerun functional-tests-backend-elasticsearch

**Comment by eranra** [comment]
On my local machine all tests passes ... I ran several times ... 

```
2018-04-16T16:43:11.512+0300	INFO	elasticsearch/client.go:266 (*ElasticSearchClient).start	SkyEran: ElasticSearchStorage started with skydive index should_roll_by_count_test
2018-04-16T16:43:18.729+0300	INFO	elasticsearch/client.go:266 (*ElasticSearchClient).start	SkyEran: ElasticSearchStorage started with skydive index should_roll_by_age_test
2018-04-16T16:43:25.876+0300	INFO	elasticsearch/client.go:266 (*ElasticSearchClient).start	SkyEran: ElasticSearchStorage started with skydive index del_indices_test
2018-04-16T16:43:26.878+0300	INFO	elasticsearch/client.go:476 (*ElasticSearchClient).rollIndex	SkyEran: Rolling indices for del_indices_test
2018-04-16T16:43:27.003+0300	INFO	elasticsearch/client.go:485 (*ElasticSearchClient).rollIndex	SkyEran: del_indices_test finished rolling indices
2018-04-16T16:43:28.012+0300	INFO	elasticsearch/client.go:476 (*ElasticSearchClient).rollIndex	SkyEran: Rolling indices for del_indices_test
2018-04-16T16:43:28.153+0300	INFO	elasticsearch/client.go:485 (*ElasticSearchClient).rollIndex	SkyEran: del_indices_test finished rolling indices
2018-04-16T16:43:29.163+0300	INFO	elasticsearch/client.go:476 (*ElasticSearchClient).rollIndex	SkyEran: Rolling indices for del_indices_test
2018-04-16T16:43:29.329+0300	INFO	elasticsearch/client.go:485 (*ElasticSearchClient).rollIndex	SkyEran: del_indices_test finished rolling indices
2018-04-16T16:43:30.340+0300	INFO	elasticsearch/client.go:476 (*ElasticSearchClient).rollIndex	SkyEran: Rolling indices for del_indices_test
2018-04-16T16:43:30.515+0300	INFO	elasticsearch/client.go:485 (*ElasticSearchClient).rollIndex	SkyEran: del_indices_test finished rolling indices
2018-04-16T16:43:31.537+0300	INFO	elasticsearch/client.go:476 (*ElasticSearchClient).rollIndex	SkyEran: Rolling indices for del_indices_test
2018-04-16T16:43:31.675+0300	INFO	elasticsearch/client.go:485 (*ElasticSearchClient).rollIndex	SkyEran: del_indices_test finished rolling indices
2018-04-16T16:43:32.875+0300	INFO	elasticsearch/client.go:266 (*ElasticSearchClient).start	SkyEran: ElasticSearchStorage started with skydive index mappings_test
2018-04-16T16:43:32.877+0300	INFO	elasticsearch/client.go:476 (*ElasticSearchClient).rollIndex	SkyEran: Rolling indices for mappings_test
2018-04-16T16:43:32.892+0300	INFO	elasticsearch/client.go:485 (*ElasticSearchClient).rollIndex	SkyEran: mappings_test finished rolling indices
PASS
```

**Comment by safchain** [comment]
rerun unit-tests

**Comment by safchain** [comment]
rerun unit-tests

**Comment by safchain** [comment]
rerun unit-tests

**Comment by safchain** [comment]
rerun functional-tests-backend-elasticsearch

**Pull request merged**
