### PR TITLE
websocket: move JSON handling from pools to clients

### PR DESCRIPTION
**Pull request by lebauce**

### CODE REVIEW

**Comment by lebauce** [comment]
run skydive-scale-tests

**Comment by lebauce** [comment]
run skydive-scale-tests

**Comment by lebauce** [comment]
run scale-tests

**Comment by lebauce** [comment]
run run scale-tests

**Comment by lebauce** [comment]
run scale-tests

**Comment by lebauce** [comment]
run tests

**Comment by lebauce** [comment]
run tests

**Comment by lebauce** [comment]
run tests

**Comment by lebauce** [comment]
run scale-tests

**Comment by lebauce** [comment]
run scale-tests

**Comment by safchain** [comment]
run tests

**Comment by safchain** [comment]
run tests

**Comment by safchain** [comment]
run tests

**Comment by safchain** [comment]
rerun tests

**Pull request merged**
