### PR TITLE
Create ansible.cfg. For a better CLI experience. For ofter testing ignoring ssh key

### PR DESCRIPTION
**Pull request by patsevanton**
For a better CLI experience. For ofter testing ignoring ssh key

### CODE REVIEW

**Comment by patsevanton** [comment]
What do you think about this Pull Request?

**Comment by safchain** [comment]
run vagrant-tests

**Comment by patsevanton** [comment]
No my errors

**Comment by safchain** [comment]
run vagrant-tests

**Comment by lebauce** [comment]
run vagrant-tests

**Pull request merged**
