### PR TITLE
istio: change edges color

### PR DESCRIPTION
**Pull request by tomerlange**
This PR changes istio edges color so they will be easily recognizable.

### CODE REVIEW

**Comment by tomerlange** [comment]
run skydive-k8s-tests

**Comment by tomerlange** [comment]
run skydive-functional-hw-tests

**Comment by tomerlange** [comment]
run skydive-functional-hw-tests

**Comment by masco-enovance** [comment]
rebase your PR to make hw-test pass

**Comment by tomerlange** [comment]
run skydive-functional-tests-backend-orientdb

**Comment by tomerlange** [comment]
run skydive-unit-tests

**Comment by tomerlange** [comment]
run skydive-functional-tests-backend-orientdb

**Pull request merged**
