### PR TITLE
gremlin: Add function for without predicate

### PR DESCRIPTION
**Pull request by masco-enovance**

### CODE REVIEW

**Comment by safchain** [comment]
rerun skydive-k8s-tests

**Comment by masco-enovance** [comment]
rerun skydive-k8s-tests

**Comment by safchain** [comment]
rerun skydive-k8s-tests

**Comment by masco-enovance** [comment]
rerun skydive-k8s-tests

**Comment by masco-enovance** [comment]
rerun skydive-k8s-tests

**Comment by masco-enovance** [comment]
run skydive-k8s-tests

**Comment by masco-enovance** [comment]
run skydive-k8s-tests

**Comment by safchain** [comment]
run skydive-k8s-tests

**Pull request merged**
