### PR TITLE
docker: bind volume qemu-<arch>-static for cross build

### PR DESCRIPTION
**Pull request by hunchback**
skip skydive-compile-tests
skip skydive-functional-hw-tests
skip skydive-functional-tests-backend-elasticsearch
skip skydive-functional-tests-backend-orientdb
skip skydive-go-fmt
skip skydive-k8s-tests
skip skydive-scale-tests
skip skydive-selenium-tests
skip skydive-unit-tests
skip skydive-cdd-overview-tests

### CODE REVIEW

**Comment by hunchback** [comment]
run skydive-ppc64-tests

**Comment by hunchback** [comment]
run tests

**Comment by hunchback** [comment]
run skydive-ppc64-tests

**Comment by hunchback** [comment]
run  skydive-create-docker-image

**Comment by safchain** [comment]
run skydive-create-docker-image

**Comment by safchain** [comment]
This one should fix the issue: #2019 
optionally we can run the following command to setup this environment:

```
docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
```

**Comment by hunchback** [comment]
The current issue is that on Ubuntu we get:

```
daily_build@iris-nvt:~/community/go/src/github.com/skydive-project/skydive$  docker run -v /usr/bin/qemu-ppc64le-static:/usr/bin/qemu-ppc64le-static -it ppc64le/debian
Unable to find image 'ppc64le/debian:latest' locally
latest: Pulling from ppc64le/debian
ed6056cee913: Pull complete
Digest: sha256:97d2acd90d1ed701ea6ea44088d0123f6cab08d729b37778b29d44fc428193cd
Status: Downloaded newer image for ppc64le/debian:latest
root@848c37eeea6a:/#
root@848c37eeea6a:/# exit
exit
daily_build@iris-nvt:~/community/go/src/github.com/skydive-project/skydive$ docker run  -it ppc64le/debian                                                      standard_init_linux.go:190: exec user process caused "no such file or directory"
daily_build@iris-nvt:~/community/go/src/github.com/skydive-project/skydive$
```

**Comment by hunchback** [comment]
run skydive-create-docker-image

**Comment by hunchback** [comment]
run skydive-create-docker-image

**Comment by eranra** [comment]
The solution we used in IBM internal build was to 'fake' Ubuntu (19.04) to include the needed qemu tools set. This works for ppc. 
As for x390x ... there is not solution as there are multiple bugs in the toolchain ... no solution for now.

**Comment by safchain** [comment]
@eranra @hunchback did you try with this 
```
docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
```
I did try on ubuntu with success with all the ARCHes

**Pull request closed without merging**
