### PR TITLE
Vagrant ansible

### PR DESCRIPTION
**Pull request by lebauce**

### CODE REVIEW

**Comment by lebauce** [comment]
run skydive-vagrant-tests

**Comment by lebauce** [comment]
run skydive-vagrant-tests

**Comment by lebauce** [comment]
run skydive-selinux-tests

**Comment by lebauce** [comment]
run skydive-vagrant-tests
run skydive-selinux-tests

**Comment by lebauce** [comment]
run skydive-vagrant-tests
run skydive-selinux-tests

**Comment by lebauce** [comment]
run skydive-vagrant-tests
run skydive-selinux-tests

**Comment by lebauce** [comment]
run skydive-vagrant-tests
run skydive-selinux-tests

**Comment by lebauce** [comment]
run skydive-selinux-tests

**Comment by lebauce** [comment]
run skydive-selinux-tests
run skydive-vagrant-tests

**Comment by lebauce** [comment]
run skydive-selinux-tests
run skydive-vagrant-tests

**Comment by lebauce** [comment]
run skydive-selinux-tests

**Comment by lebauce** [comment]
run skydive-vagrant-tests

**Comment by lebauce** [comment]
run skydive-selinux-tests
run skydive-vagrant-tests

**Comment by lebauce** [comment]
run skydive-selinux-tests

**Comment by lebauce** [comment]
run skydive-selinux-tests

**Comment by lebauce** [comment]
run skydive-vagrant-tests

**Comment by lebauce** [comment]
run skydive-selinux-tests

**Comment by lebauce** [comment]
run skydive-vagrant-tests

**Comment by lebauce** [comment]
run skydive-selinux-tests

**Comment by lebauce** [comment]
run skydive-selinux-tests

**Comment by lebauce** [comment]
run skydive-selinux-tests

**Comment by lebauce** [comment]
run skydive-selinux-tests

**Comment by lebauce** [comment]
run skydive-selinux-tests

**Comment by lebauce** [comment]
run skydive-selinux-tests
run skydive-vagrant-tests

**Comment by lebauce** [comment]
run skydive-selinux-tests
run skydive-vagrant-tests

**Comment by lebauce** [comment]
run skydive-vagrant-tests

**Comment by safchain** [comment]
run skydive-selinux-tests

**Comment by lebauce** [comment]
run skydive-go-fmt
run skydive-functional-tests-backend-elasticsearch
run skydive-functional-tests-backend-orientdb
run skydive-scale-tests
run skydive-cdd-overview-tests
run skydive-unit-tests
run skydive-compile-tests
run skydive-k8s-tests
run skydive-functional-hw-tests

**Comment by lebauce** [comment]
run skydive-selinux-tests

**Pull request merged**
