### PR TITLE
socketinfo: fix compilation on old kernels

### PR DESCRIPTION
**Pull request by lebauce**

### CODE REVIEW

**Comment by lebauce** [comment]
run skydive-functional-tests-backend-orientdb

**Comment by lebauce** [comment]
run skydive-functional-tests-backend-orientdb

**Comment by masco-enovance** [comment]
run skydive-functional-tests-backend-orientdb

**Comment by masco-enovance** [comment]
run functional-tests-backend-elasticsearch

**Comment by safchain** [comment]
rerun functional-tests-backend-orientdb

**Pull request merged**
