### PR TITLE
Openflow json

### PR DESCRIPTION
**Pull request by pierrecregut**
Schema and parser for openflow rules.

### CODE REVIEW

**Comment by pierrecregut** [comment]
Just for discussion on the proposed Json schema.
It only covers rules, not groups and is pretty verbose. 
The parser is not ready yet.

**Comment by pierrecregut** [comment]
The updated version modify the schema to make it less verbose (there is still a **very high overhead**). Note that the schema does not really distinguish values and functions in actions. It would be hard to do without a well known set of actions that we would then need to maintain.

The unit tests should give a good idea of what one can expect as output.

There is still no link with skydive. If we use it, it will mean that we have an unparser in the front-end.
We also need to add support for *parsing groups* (and handling meters would be nice too at least at the level of schemas).

**Comment by pierrecregut** [comment]
openflow-json-overhead

Here is a chart of the ratio of the size of the json encoding and the original encoding for the 44000 rules extracted from the openvswitch test suite. The mean is 2.17

Similar results can be obtained for groups but the test suite is much shorter:
openflow-json-overhead-groups

**Comment by safchain** [comment]
@pierrecregut Thanks for this WIP patch and the inputs, I'm going to start playing with it.

**Comment by pierrecregut** [comment]
Last update adds a third commit that enables the new openflow -> json parser in the openflow probe.
As it impacts the metadata of rules, ui and functional tests have been updated.

**Comment by pierrecregut** [comment]
run skydive-cdd-overview-tests

**Comment by lebauce** [comment]
@pierrecregut Thank a lot for this, it definitely makes querying rules with Gremlin easier.

We recently introduced the possibility to define a schema for metadata in https://github.com/skydive-project/skydive/pull/1427 (this commit shows how to convert an existing probe https://github.com/skydive-project/skydive/pull/1427/commits/aa24aff1903895d714df20ba4439d072e4c564ba). This way, you could define a Go struct for an OpenFlow rule.

Regarding the structure, I would prefer to not create an other `Meta` level inside the metadata. `duration`, `reset_counts`, ... could be at the same level than 'priority`, `cookie` and others. For flags such as `reset_counts`, they could be converted to booleans instead of using a key/value with an empty value.

It would be nice if they could be converted to camel case (`Priority`, `Cookie`, `ResetCounts`) as it's the convention we have been following so far for metadata.

Maybe in a latter PR, we could also allow the user to use the `Metrics` step on OpenFlow rules so that we can do this such as `g.V().Has('Type, 'ofrule', .....).Metrics().Aggregates() to get and graph the metrics for a set of rules.

For filters, it would be more user friendly to rename "k" to "Name", "v" to "Value", and "m" to "Match".
For actions, we could rename "f" to "Name", and "a" to "Args".

This way, we could write nicer Gremlin queries such as :
```
g.V().Has('Type', 'ofrule', 'OpenFlow.Priority', GT(150), 'OpenFlow.Action.Name', 'resubmit')
```

**Comment by pierrecregut** [comment]
@lebauce please keep in mind that the probe does not understand Openflow. The Meta struct is probably misnamed (Extra ?) but I don't think its content should be mixed with the part Priority/Table/Filters/Actions that is well defined. For example if you transform the "n" field of Meta to a key in a dictionnary, you will loose the ability to type the schema. For similar reason, flags cannot be transformed into booleans: we just do not know they exist when they are not present. If the reason to do so are Gremlin limitations, we should think of an xpath equivalent for gremlin (JSONPath ?).

Do not forget the overhead of this proposal (see my graph above). My first try used full words as name/value/mask. From my point of view it proved to be too verbose (ratio size json/size original was much higher). 

For capitalized field names, no problem even if it feels like a go convention pushed to json. 
Do we want to have our format adopted outside skydive ? An idea proposed at the hackaton was to push the json format description to the openvswitch community so that the tools generate it directly when they are used with the right flag.

Gremlin filters will be possible but remember that filters are lists and actions are often trees. Can we have list predicates like any, forall on lists with Has ? Again, we need some kind of JSONPath.

**Comment by safchain** [comment]
@pierrecregut I think having "real name" for the fields makes sense even with a the lite overhead, it will bring readability and will help users to understand what they see. For the JSONPath why not but I would start making this usable even with a reduced perimeter. 

Pushing the json to the ovs community sounds good but maybe we should try to use it/improve it to make sure that it fits our needs. (not only ours)
I think some of the fields in the schema could be enforced as their name and type are known (priority, etc.), but that can be done later probably.

**Comment by pierrecregut** [comment]
I will rebase it on top of #1499 when it is merged.
Regarding the name fields, I am glad HTML did not impose "Bold", "Anchor" or "Italic" for common tag names.

**Comment by lebauce** [comment]
@pierrecregut :-) That's a - probably - poor design choice on our side. But being consistent is important otherwise the user needs to know for every field if it's uppercase or lowercase

**Comment by safchain** [comment]
I'm glad iptables imposes upper case for tables, or that c, javascript etc are case sensitive :) Please keep in mind that there are other contributors and that we have to maintain the whole project for a long term and we try to keep things consistant.

**Comment by pierrecregut** [comment]
The rambling was rather against long names that become distracting rather than informative when they are repeated too much (look at the unit tests).
The only problem with capitalized fields is that it is not javascript conventions. Conventions tend to come back in unexpected ways (see metadata vs Metadata...). Also it would be easier to make it acceptable by another community if we want to submit our format.

**Comment by safchain** [comment]
This not about javascript, this is about API (gremlin), etc. We should not consider the WebUI thing here. I had a look a the unit test and that is why I think that is important to make them readable otherwise I don't really know what "f" means. Regarding the format that we would send to ovs, there will be changes for sure requested by them and we can't predict them so I'll be focus on our current use case then if the schema change we will adapt.

**Comment by lebauce** [comment]
@pierrecregut I pushed a PR (https://github.com/skydive-project/skydive/pulls) on top of your branch. It introduces a pure Go OpenFlow parser in addition to the ovs-ofctl one. Your PR is still marked as WIP, is it still true ? Thanks

**Comment by pierrecregut** [comment]
I think we can remove the WIP. But I commited a last change : the schema was out of sync with the produced json (It still used short names).

**Comment by pierrecregut** [comment]
All the commits have been merged in #1474, I am not sure I understand why but there is probably no reason to keep it open.

**Comment by lebauce** [comment]
@pierrecregut ovs-ofctl and native versions share a bunch of code. It was also more convenient to test to ensure there was no regression with the native version. It was therefore a lot easier to put both version in the same PR

**Pull request closed without merging**
