### PR TITLE
K8s deployment probe

### PR DESCRIPTION
**Pull request by hunchback**
Can be tested using:

```
k8s:
  probes:
    deployment
```

### CODE REVIEW

**Comment by nplanel** [comment]
ok to test

**Comment by hunchback** [comment]
I have moved to deployment version `apiVersion: extensions/v1beta1` (which should be compatible with the existing version of minikube used on CI.

**Comment by hunchback** [comment]
The test failed due to an unrelated bug in definition of k8s pod test (timeout being too small, thus not waiting enough time for the pod object to be created):

```
Gremlin Query: G.V().Has("Manager", "k8s", "Type", "pod", "Name", Regex("skydive-test-pod.*"))
Gremlin Query: G.V().Has("Manager", "k8s", "Type", "pod", "Name", Regex("skydive-test-pod.*"))
Gremlin Query: G.V().Has("Manager", "k8s", "Type", "pod", "Name", Regex("skydive-test-pod.*"))
2018-05-02 17:07:33.678497 W | wal: sync duration of 2.324189128s, expected less than 1s
2018-05-02T17:07:33.769Z	DEBUG	topology/topology.go:137 AddOwnershipLink	jenkins-slave-6.rdocloud: Delete previous ownership link: {"ID":"2a5cfad9-7e14-58a8-4d89-a05d1637ab18","Metadata":{"RelationType":"ownership"},"Parent":"f8469f10-2c36-4a97-55fd-e46682c989ad","Child":"dc4d8d6a-4c77-11e8-9119-fa163ebf9b9a","Host":"jenkins-slave-6.rdocloud","CreatedAt":1525280842490,"UpdatedAt":1525280842490}
2018-05-02 17:07:34.993211 W | wal: sync duration of 1.138781179s, expected less than 1s
2018-05-02T17:07:35.476Z	DEBUG	helper/helper.go:135 ExecCmds	jenkins-slave-6.rdocloud: Executing command [kubectl delete deployment skydive-test-pod]
2018-05-02T17:07:37.390Z	DEBUG	flow/table.go:239 (*Table).update	jenkins-slave-6.rdocloud: flow table update: 1525280847389, 1525280857389
2018-05-02 17:07:38.123841 W | wal: sync duration of 3.130225976s, expected less than 1s
2018-05-02T17:07:38.127Z	DEBUG	k8s/container.go:154 (*containerProbe).OnAdd	jenkins-slave-6.rdocloud: Creating container nodes for pod{Namespace: default, Name: skydive-test-pod-7f9df6ddf6-2ljgj}
2018-05-02T17:07:38.129Z	DEBUG	k8s/deployment.go:71 (*deployProbe).OnUpdate	jenkins-slave-6.rdocloud: Updated deployment{Name: skydive-test-pod}
2018-05-02T17:07:38.129Z	DEBUG	k8s/container.go:131 (*containerProbe).onContainerAdd	jenkins-slave-6.rdocloud: Adding container{podNamespace: default, podName: skydive-test-pod-7f9df6ddf6-2ljgj, containerName: skydive-test-pod}
2018-05-02T17:07:38.130Z	DEBUG	k8s/container.go:102 (*containerProbe).linkContainerToPod	jenkins-slave-6.rdocloud: Can't find pod{Namespace: default, Name: skydive-test-pod-7f9df6ddf6-2ljgj}
2018-05-02T17:07:38.131Z	DEBUG	k8s/container.go:114 (*containerProbe).linkContainerToDocker	jenkins-slave-6.rdocloud: Can't find docker associated with container{podNamespace: default, podName: skydive-test-pod-7f9df6ddf6-2ljgj, containerName: skydive-test-pod}
2018-05-02T17:07:38.131Z	DEBUG	k8s/pod.go:117 (*podProbe).OnAdd	jenkins-slave-6.rdocloud: Creating node for pod{Namespace: default, Name: skydive-test-pod-7f9df6ddf6-2ljgj}
2018-05-02T17:07:38.133Z	DEBUG	k8s/namespace.go:126 (*namespaceProbe).OnNodeAdded	jenkins-slave-6.rdocloud: Got event on adding pod{Namespace: default, Name: skydive-test-pod-7f9df6ddf6-2ljgj}
2018-05-02T17:07:38.133Z	DEBUG	k8s/namespace.go:83 (*namespaceProbe).linkObject	jenkins-slave-6.rdocloud: Added link: namespace{Namespace: , Name: default} -> pod{Namespace: default, Name: skydive-test-pod-7f9df6ddf6-2ljgj}
2018-05-02T17:07:39.118Z	DEBUG	k8s/container.go:163 (*containerProbe).OnUpdate	jenkins-slave-6.rdocloud: Updating container nodes of pod{Namespace: default, Name: skydive-test-pod-7f9df6ddf6-2ljgj}
2018-05-02T17:07:39.118Z	DEBUG	k8s/container.go:134 (*containerProbe).onContainerAdd	jenkins-slave-6.rdocloud: Updating container{podNamespace: default, podName: skydive-test-pod-7f9df6ddf6-2ljgj, containerName: skydive-test-pod} (as it already exists)
2018-05-02T17:07:39.119Z	DEBUG	k8s/container.go:106 (*containerProbe).linkContainerToPod	jenkins-slave-6.rdocloud: Linking container{podNamespace: default, podName: skydive-test-pod-7f9df6ddf6-2ljgj, containerName: skydive-test-pod} to pod{Namespace: default, Name: skydive-test-pod-7f9df6ddf6-2ljgj}
2018-05-02T17:07:39.120Z	DEBUG	k8s/container.go:114 (*containerProbe).linkContainerToDocker	jenkins-slave-6.rdocloud: Can't find docker associated with container{podNamespace: default, podName: skydive-test-pod-7f9df6ddf6-2ljgj, containerName: skydive-test-pod}
2018-05-02T17:07:39.120Z	DEBUG	k8s/pod.go:139 (*podProbe).OnUpdate	jenkins-slave-6.rdocloud: Updating node for pod{Namespace: default, Name: skydive-test-pod-7f9df6ddf6-2ljgj}
2018-05-02T17:07:39.149Z	DEBUG	k8s/deployment.go:71 (*deployProbe).OnUpdate	jenkins-slave-6.rdocloud: Updated deployment{Name: skydive-test-pod}
2018-05-02T17:07:39.150Z	DEBUG	docker/docker.go:95 (*DockerProbe).registerContainer	jenkins-slave-6.rdocloud: Register docker container 510ca77d8deba226ea87ffdda9af905447b6fc210b888d2aab71838ad2a35647 and PID 20602
2018-05-02T17:07:39.150Z	DEBUG	netns/netns.go:122 (*NetNSProbe).Register	jenkins-slave-6.rdocloud: Register network namespace: /proc/20602/ns/net
2018-05-02T17:07:39.150Z	DEBUG	netns/netns.go:151 (*NetNSProbe).Register	jenkins-slave-6.rdocloud: Increasing counter for namespace 3,4026536796 to 2
2018-05-02T17:07:39.194Z	DEBUG	k8s/deployment.go:71 (*deployProbe).OnUpdate	jenkins-slave-6.rdocloud: Updated deployment{Name: skydive-test-pod}
2018-05-02T17:07:39.411Z	DEBUG	k8s/deployment.go:71 (*deployProbe).OnUpdate	jenkins-slave-6.rdocloud: Updated deployment{Name: skydive-test-pod}
2018-05-02T17:07:39.426Z	DEBUG	k8s/deployment.go:71 (*deployProbe).OnUpdate	jenkins-slave-6.rdocloud: Updated deployment{Name: skydive-test-pod}
2018-05-02T17:07:39.441Z	DEBUG	k8s/deployment.go:71 (*deployProbe).OnUpdate	jenkins-slave-6.rdocloud: Updated deployment{Name: skydive-test-pod}
2018-05-02T17:07:39.447Z	DEBUG	k8s/pod.go:139 (*podProbe).OnUpdate	jenkins-slave-6.rdocloud: Updating node for pod{Namespace: default, Name: skydive-test-pod-7f9df6ddf6-2ljgj}
```

**Comment by safchain** [comment]
rerun selenium-tests

**Comment by lebauce** [comment]
@hunchback Can you please rebase ?

**Comment by hunchback** [comment]
@lebauce - I have rebased (plus added a small extra commit)

**Comment by hunchback** [comment]
@lebauce - can you check why orientdb failed?

**Pull request merged**
