### PR TITLE
ui: use default filter if not filter given and fix resync

### PR DESCRIPTION
**Pull request by safchain**
skip skydive-compile-tests
skip skydive-functional-tests-backend-elasticsearch
skip skydive-functional-tests-backend-orientdb
skip skydive-go-fmt
skip skydive-k8s-tests
skip skydive-scale-tests
skip skydive-selenium-tests
skip skydive-unit-tests
skip skydive-ppc64-tests

### CODE REVIEW

**Comment by safchain** [comment]
@eranra can you have a look at this please ? it should fixe the G.V() sync thing

**Comment by safchain** [comment]
run skydive-functional-hw-tests

**Comment by eranra** [comment]
@safchain Yes ... I will look on this ... can't find time :-(

**Comment by eranra** [comment]
@safchain Hi. I finally had time to check ... it works perfectly :-) Huge change when we have scalable environment.

**Pull request merged**
