### PR TITLE
Bump Go version to 1.8

### PR DESCRIPTION
**Pull request by lebauce**

### CODE REVIEW

**Comment by safchain** [comment]
run packaging

**Comment by safchain** [comment]
run packaging-tests

**Comment by safchain** [comment]
run packaging-tests

**Comment by safchain** [comment]
run devstack-plugin

**Comment by safchain** [comment]
run devstack

**Comment by safchain** [comment]
run devstack

**Comment by safchain** [comment]
run devstack

**Comment by nplanel** [comment]
don't forget travis

**Comment by nplanel** [comment]
in rpm change 1.5 => 1.8
BuildRequires:  %{?go_compiler:compiler(go-compiler)}%{!?go_compiler:golang} >= 1.5

**Pull request merged**
