### PR TITLE
ovsdb: fix race in openflow probe

### PR DESCRIPTION
**Pull request by lebauce**

### CODE REVIEW

**Comment by safchain** [comment]
run  skydive-functional-tests-backend-elasticsearch

**Comment by safchain** [comment]
run  skydive-functional-tests-backend-elasticsearch

**Comment by safchain** [comment]
run  skydive-functional-tests-backend-elasticsearch

**Comment by lebauce** [comment]
run skydive-functional-tests-backend-elasticsearch
run skydive-ppc64le-tests

**Pull request merged**
