### PR TITLE
k8s/tests: apply and delete of contrib/kubernetes/skydive.yaml

### PR DESCRIPTION
**Pull request by hunchback**
to verify this works just time here:

```
run skydive-k8s-tests
```

### CODE REVIEW

**Comment by hunchback** [comment]
run skydive-functional-hw-tests

**Comment by hunchback** [comment]
run skydive-cdd-overview-tests

**Comment by lebauce** [comment]
@hunchback It would be very nice to make actual requests to the deployed Skydive (otherwise we don't really know if that actually works)

**Comment by hunchback** [comment]
https://github.com/skydive-project/skydive/pull/1714#issuecomment-475564072

The k8s approach is to add health checks (within the YAML), just as was implemented for helm, this is an further enhancement to the yaml which i rather handle in a seperate PR ...

**Comment by hunchback** [comment]
run skydive-functional-hw-tests

**Comment by lebauce** [comment]
@hunchback Can you please rebase this PR ? Thanks

**Comment by lebauce** [comment]
run skydive-functional-hw-tests

**Pull request merged**
