### PR TITLE
allinone: fix permission issue with file logging

### PR DESCRIPTION
**Pull request by lebauce**

### CODE REVIEW

**Comment by safchain** [comment]
run devstack

**Comment by safchain** [comment]
run devstack

**Comment by safchain** [comment]
run devstack

**Comment by lebauce** [comment]
run devstack

**Comment by safchain** [comment]
run devstack

**Comment by lebauce** [comment]
run devstack

**Comment by lebauce** [comment]
run scale-tests

**Comment by lebauce** [comment]
run functional-tests-backend-elasticsearch

**Comment by lebauce** [comment]
run scale-tests

**Comment by lebauce** [comment]
run functional-tests-backend-orientdb

**Comment by lebauce** [comment]
run skydive-functional-tests-backend-orientdb

**Comment by lebauce** [comment]
run tests

**Comment by lebauce** [comment]
run skydive-coverage

**Comment by lebauce** [comment]
run skydive-functional-tests-backend-orientdb

**Comment by lebauce** [comment]
run skydive-scale-tests

**Pull request merged**
