### PR TITLE
Add support self yum repository to package.yml

### PR DESCRIPTION
**Pull request by patsevanton**

### CODE REVIEW

**Comment by safchain** [comment]
run skydive-vagrant-tests

**Comment by patsevanton** [comment]
```
ERROR: Exception(rpmbuild/SRPMS/skydive-0.25.0-0.33ccc873b311.tainted.src.rpm) Config(epel-7-x86_64) 2 minutes 40 seconds

ERROR: state finish mismatch: current: rpmbuild skydive-0.25.0-0.33ccc873b311.tainted.src.rpm, state: build phase for skydive-0.25.0-0.33ccc873b311.tainted.src.rpm
```

My error?

**Comment by safchain** [comment]
@patsevanton I'm checking right now, I don't think this is because of your PR

**Comment by safchain** [comment]
We just merged the fix, can you please rebase on top of master

**Comment by patsevanton** [comment]
rebase

**Comment by safchain** [comment]
run skydive-vagrant-tests
run skydive-cdd-overview-tests

**Comment by patsevanton** [comment]
```
goroutine 95 [select]:
net/http.(*persistConn).writeLoop(0xc000582a20)
	/var/lib/jenkins/.gimme/versions/go1.11.13.linux.amd64/src/net/http/transport.go:1887 +0x1b3
created by net/http.(*Transport).dialConn
	/var/lib/jenkins/.gimme/versions/go1.11.13.linux.amd64/src/net/http/transport.go:1341 +0xb4e
make[1]: *** [.mk/tests.mk:79: test.functionals.run] Error 2
make[1]: Leaving directory '/var/lib/jenkins/workspace/skydive-cdd-overview-tests/src/github.com/skydive-project/skydive'
make: *** [.mk/tests.mk:91: test.functionals] Error 2```

**Pull request closed without merging**
