### PR TITLE
client: remove origin from python client

### PR DESCRIPTION
**Pull request by masco-enovance**

### CODE REVIEW

**Comment by masco-enovance** [comment]
run python-tests

**Comment by masco-enovance** [comment]
run python-tests

**Comment by masco-enovance** [comment]
run python-tests

**Comment by masco-enovance** [comment]
run functional-tests-backend-orientdb
run skydive-ppc64le-tests
run python-tests

**Comment by masco-enovance** [comment]
run skydive-ppc64le-tests
run python-tests

**Comment by masco-enovance** [comment]
run python-tests

**Comment by masco-enovance** [comment]
run python-tests

**Comment by safchain** [comment]
run python-tests

**Comment by safchain** [comment]
need to be rebased

**Comment by masco-enovance** [comment]
run skydive-functional-tests-backend-orientdb
run skydive-python-tests
run skydive-scale-tests

**Pull request merged**
