### PR TITLE
devstack plugin: update the go version

### PR DESCRIPTION
**Pull request by masco**
skip skydive-go-fmt
skip skydive-functional-tests-backend-elasticsearch
skip skydive-functional-tests-backend-orientdb
skip skydive-scale-tests
skip skydive-cdd-overview-tests
skip skydive-unit-tests
skip skydive-compile-tests
skip skydive-k8s-tests
skip skydive-ppc64le-tests
skip skydive-functional-hw-tests

### CODE REVIEW

**Comment by lebauce** [comment]
We should also set up GO111MODULE=on (just after setting GOPATH for instance)

**Comment by lebauce** [comment]
run devstack-tests

**Comment by masco** [comment]
run devstack-tests

**Comment by safchain** [comment]
run skydive-devstack-tests

**Comment by safchain** [comment]
this needs to be modified as well 
https://github.com/skydive-project/skydive/blob/master/scripts/ci/devstack/run-openstack-tests.sh#L11

**Comment by masco** [comment]
run skydive-devstack-tests

**Comment by lebauce** [comment]
run skydive-devstack-tests

**Comment by lebauce** [comment]
run devstack-tests

**Comment by lebauce** [comment]
run devstack-tests

**Comment by masco** [comment]
run devstack-tests

**Comment by masco** [comment]
run devstack-tests

**Comment by lebauce** [comment]
run devstack-tests

**Comment by lebauce** [comment]
run devstack-tests

**Comment by lebauce** [comment]
run devstack-tests

**Comment by lebauce** [comment]
run devstack-tests

**Comment by lebauce** [comment]
run devstack-tests

**Comment by lebauce** [comment]
run devstack-tests

**Comment by lebauce** [comment]
run devstack-tests

**Pull request merged**
