### PR TITLE
ci: fix create docker image

### PR DESCRIPTION
**Pull request by hunchback**

### CODE REVIEW

**Comment by hunchback** [comment]
skip skydive-compile-tests
skip skydive-functional-hw-tests
skip skydive-functional-tests-backend-elasticsearch
skip skydive-functional-tests-backend-orientdb
skip skydive-go-fmt
skip skydive-k8s-tests
skip skydive-scale-tests
skip skydive-selenium-tests
skip skydive-unit-tests
skip skydive-cdd-overview-tests
skip skydive-ppc64-tests

**Comment by hunchback** [comment]
rerun tests

**Comment by safchain** [comment]
run skydive-functional-tests-backend-elasticsearch
run skydive-functional-tests-backend-orientdb
run skydive-cdd-overview-tests

**Comment by safchain** [comment]
run skydive-cdd-overview-tests

**Pull request merged**
