### PR TITLE
Ui color themes

### PR DESCRIPTION
**Pull request by hunchback**
You can now switch between two theme via configuration (if not set then using `dark`)

Set theme from configuration UI section:
```
ui:
  theme: {light,dark} 
```
Set theme from URL 
```
http://<host>:8082/topology?theme={light,dark}
```

### CODE REVIEW

**Comment by safchain** [comment]
run cdd-overview

**Comment by hunchback** [comment]
@safchain - any additional comments?

**Comment by safchain** [comment]
I did test it quickly, I'm quite OK with the approach. Still some css to rework for the white theme, I need more time to review it deeply.

**Comment by hunchback** [comment]
have rebased

**Comment by hunchback** [comment]
@safchain - any pending issues here?

**Comment by safchain** [comment]
ok to test

**Comment by safchain** [comment]
@hunchback I think still some css color issues, but I guess that something we can fix later, let me retest it and I will merge it

**Comment by safchain** [comment]
@hunchback is it OK for you to apply this
https://paste.fedoraproject.org/paste/G96goRFG9c2-mbmvTnNVSA

I just fixed some color/readability issue

**Comment by hunchback** [comment]
@safchain - ok applied your fixes

**Pull request merged**
