### PR TITLE
K8s tests

### PR DESCRIPTION
**Pull request by lebauce**

### CODE REVIEW

**Comment by hunchback** [comment]
Failed `skydive-scale-tests` due to:

```
12:33:25.734 --- FAIL: TestScaleHA (139.53s)
12:33:25.734 	scale_test.go:366: Should return 4 host nodes got : [{"ID":"eb545698-ebb0-45c0-7991-f5f518157a98","Metadata":{"CPU":[{"CacheSize":12288,"CoreID":"0","Cores":1,"Family":"6","Mhz":2394,"Microcode":"0x10","Model":"44","ModelName":"Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz","PhysicalID":"1","Stepping":2,"VendorID":"GenuineIntel"},{"CPU":1,"CacheSize":12288,"CoreID":"0","Cores":1,"Family":"6","Mhz":2394,"Microcode":"0x10","Model":"44","ModelName":"Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz","PhysicalID":"0","Stepping":2,"VendorID":"GenuineIntel"},{"CPU":2,"CacheSize":12288,"CoreID":"1","Cores":1,"Family":"6","Mhz":2394,"Microcode":"0x10","Model":"44","ModelName":"Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz","PhysicalID":"1","Stepping":2,"VendorID":"GenuineIntel"},{"CPU":3,"CacheSize":12288,"CoreID":"1","Cores":1,"Family":"6","Mhz":2394,"Microcode":"0x10","Model":"44","ModelName":"Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz","PhysicalID":"0","Stepping":2,"VendorID":"GenuineIntel"},{"CPU":4,"CacheSize":12288,"CoreID":"9","Cores":1,"Family":"6","Mhz":2394,"Microcode":"0x10","Model":"44","ModelName":"Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz","PhysicalID":"1","Stepping":2,"VendorID":"GenuineIntel"},{"CPU":5,"CacheSize":12288,"CoreID":"9","Cores":1,"Family":"6","Mhz":2394,"Microcode":"0x10","Model":"44","ModelName":"Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz","PhysicalID":"0","Stepping":2,"VendorID":"GenuineIntel"},{"CPU":6,"CacheSize":12288,"CoreID":"10","Cores":1,"Family":"6","Mhz":2394,"Microcode":"0x10","Model":"44","ModelName":"Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz","PhysicalID":"1","Stepping":2,"VendorID":"GenuineIntel"},
```

**Comment by hunchback** [comment]
Fixed `gremlin/query.go` in the original PR,
Addressing issue in `host_id` in a different PR

**Comment by lebauce** [comment]
run skydive-functional-tests-backend-orientdb

**Comment by safchain** [comment]
rerun functional-tests-backend-orientdb

**Comment by lebauce** [comment]
rerun skydive-selenium-tests

**Comment by lebauce** [comment]
rerun skydive-functional-tests-backend-elasticsearch

**Comment by hunchback** [comment]
Failed due to:

```
17:46:20.293 FATAL: command execution failed
17:46:20.294 java.io.IOException: No route to host
17:46:20.294 	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
17:46:20.294 	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
17:46:20.294 	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
17:46:20.294 	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
17:46:20.294 	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
17:46:20.294 	at org.jenkinsci.remoting.nio.FifoBuffer$Pointer.receive(FifoBuffer.java:142)
17:46:20.294 	at org.jenkinsci.remoting.nio.FifoBuffer.receive(FifoBuffer.java:359)
17:46:20.294 	at org.jenkinsci.remoting.nio.NioChannelHub.run(NioChannelHub.java:564)
17:46:20.294 Caused: java.io.IOException: Connection aborted: org.jenkinsci.remoting.nio.NioChannelHub$MonoNioTransport@81f2dda[name=Channel to /149.14.153.26]
17:46:20.294 	at org.jenkinsci.remoting.nio.NioChannelHub$NioTransport.abort(NioChannelHub.java:210)
17:46:20.294 	at org.jenkinsci.remoting.nio.NioChannelHub.run(NioChannelHub.java:635)
17:46:20.294 	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
17:46:20.294 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
17:46:20.294 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
17:46:20.294 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
17:46:20.294 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
17:46:20.294 	at java.lang.Thread.run(Thread.java:748)
17:46:20.294 Caused: java.io.IOException: Backing channel 'Channel to /149.14.153.26' is disconnected.
17:46:20.294 	at hudson.remoting.RemoteInvocationHandler.channelOrFail(RemoteInvocationHandler.java:192)
17:46:20.294 	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:257)
17:46:20.294 	at com.sun.proxy.$Proxy86.isAlive(Unknown Source)
17:46:20.294 	at hudson.Launcher$RemoteLauncher$ProcImpl.isAlive(Launcher.java:1138)
17:46:20.294 	at hudson.Launcher$RemoteLauncher$ProcImpl.join(Launcher.java:1130)
17:46:20.294 	at hudson.tasks.CommandInterpreter.join(CommandInterpreter.java:155)
17:46:20.294 	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:109)
17:46:20.294 	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:66)
17:46:20.294 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
17:46:20.294 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:730)
17:46:20.294 	at hudson.model.Build$BuildExecution.build(Build.java:206)
17:46:20.294 	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
17:46:20.294 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:490)
17:46:20.294 	at hudson.model.Run.execute(Run.java:1735)
17:46:20.294 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
17:46:20.294 	at hudson.model.ResourceController.execute(ResourceController.java:97)
17:46:20.294 	at hudson.model.Executor.run(Executor.java:415)
17:46:20.298 Build step 'Execute shell' marked build as failure
17:46:20.304 Setting status of 3bdd54f8c5b7eb14d9402a3e8eeecbb4a60e41f6 to FAILURE with url https://ci.skydive.network/job/skydive-scale-tests/1913/ and message: 'Build finished. '
17:46:20.305 Using context: skydive-scale-tests
17:47:16.361 Could not update commit status of the Pull Request on GitHub.
17:47:16.362 java.net.UnknownHostException: api.github.com
17:47:16.362 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
17:47:16.362 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
17:47:16.362 	at java.net.Socket.connect(Socket.java:589)
17:47:16.362 	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
17:47:16.362 	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
17:47:16.362 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
17:47:16.362 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
17:47:16.363 	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
17:47:16.363 	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
17:47:16.363 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
17:47:16.363 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
17:47:16.363 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
17:47:16.364 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
17:47:16.364 	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1316)
17:47:16.364 	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1291)
17:47:16.364 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:250)
17:47:16.364 	at org.kohsuke.github.Requester.buildRequest(Requester.java:405)
17:47:16.364 	at org.kohsuke.github.Requester._to(Requester.java:269)
17:47:16.365 	at org.kohsuke.github.Requester.to(Requester.java:234)
17:47:16.365 	at org.kohsuke.github.GHRepository.createCommitStatus(GHRepository.java:1075)
17:47:16.365 	at org.jenkinsci.plugins.ghprb.extensions.status.GhprbSimpleStatus.createCommitStatus(GhprbSimpleStatus.java:272)
17:47:16.365 	at org.jenkinsci.plugins.ghprb.extensions.status.GhprbSimpleStatus.onBuildComplete(GhprbSimpleStatus.java:231)
17:47:16.365 	at org.jenkinsci.plugins.ghprb.GhprbBuilds.onCompleted(GhprbBuilds.java:192)
17:47:16.365 	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onCompleted(GhprbBuildListener.java:26)
17:47:16.366 	at hudson.model.listeners.RunListener.fireCompleted(RunListener.java:211)
17:47:16.366 	at hudson.model.Run.execute(Run.java:1780)
17:47:16.366 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
17:47:16.366 	at hudson.model.ResourceController.execute(ResourceController.java:97)
17:47:16.366 	at hudson.model.Executor.run(Executor.java:415)
17:47:16.366 Finished: FAILURE
```

**Comment by hunchback** [comment]
@lebauce - is this pending on me?

**Comment by hunchback** [comment]
@lebauce @safchain - let me know what is needed to get this through - this is just a first step - once in I will be able to extend k8s tests to achieve extended coverage.

**Comment by lebauce** [comment]
run skydive-go-fmt

**Pull request merged**
