### PR TITLE
fabric: dynamically add fabric node and links

### PR DESCRIPTION
**Pull request by masco**

### CODE REVIEW

**Comment by jonnary** [comment]
Hi, masco.  Why we didn't merge this commit?
Maybe we can do this together.

**Comment by masco-enovance** [comment]
Hey Jonnary, thanks for your interest. We have added one generic way to add/edit nodes and edges. with that, we can create fabric nodes also. This is no more needed. I will discard this soon. thanks!
cmd to use the generic way: skydive client node-rule & skydive client edge-rule.

**Comment by jonnary** [comment]
ok. I have test the new patch. Many things need to continue to work about external switch.

**Comment by lebauce** [comment]
Efforts moved to new UI

**Pull request closed without merging**
