### PR TITLE
ansible: workaround regex

### PR DESCRIPTION
**Pull request by nplanel**
due to python 3.7 issue : https://bugs.python.org/issue32308

### CODE REVIEW

**Comment by nplanel** [comment]
run skydive-vagrant-tests

**Comment by nplanel** [comment]
run skydive-vagrant-tests

**Comment by nplanel** [comment]
run skydive-vagrant-tests

**Comment by nplanel** [comment]
run skydive-functional-tests-backend-orientdb

**Comment by nplanel** [comment]
run skydive-vagrant-tests

**Comment by nplanel** [comment]
run skydive-functional-tests-backend-orientdb

**Comment by lebauce** [comment]
run skydive-python-tests

**Pull request merged**
