### PR TITLE
ui: add routing-table component

### PR DESCRIPTION
**Pull request by eonpatapon**
This display the routing tables in a nicer way

### CODE REVIEW

**Comment by nplanel** [comment]
run skydive-compile-tests

**Comment by nplanel** [comment]
run skydive-compile-tests

**Comment by nplanel** [comment]
run skydive-compile-tests

**Comment by nplanel** [comment]
run skydive-compile-tests

**Comment by nplanel** [comment]
run skydive-compile-tests

**Comment by nplanel** [comment]
run skydive-compile-tests

**Comment by nplanel** [comment]
run skydive-compile-tests

**Comment by nplanel** [comment]
run skydive-compile-tests

**Comment by nplanel** [comment]
run skydive-compile-tests

**Comment by nplanel** [comment]
run skydive-compile-tests

**Comment by safchain** [comment]
rerun compile-tests

**Comment by safchain** [comment]
rerun skydive-compile-tests

**Comment by safchain** [comment]
rerun tests

**Comment by safchain** [comment]
rerun tests

**Comment by safchain** [comment]
@eonpatapon It seems that the selenium test has to be updated to work according to your modification
http://ci-logs.skydive.network/skydive-selenium-tests/builds/228/log.html

**Comment by eonpatapon** [comment]
I've run the selenium test 2 times on my machine with success
2 times it failed with: `selenium_test.go:177: By default 8 rows should be return, but got: 3`

Running it with: `make test.functionals WITH_SELENIUM=true VERBOSE=true TIMEOUT=10m TEST_PATTERN=PacketInjectionCapture ARGS="$ARGS -standalone"`

**Comment by eonpatapon** [comment]
rerun skydive-selenium-tests

**Comment by eonpatapon** [comment]
it has passed, running it again

**Comment by eonpatapon** [comment]
rerun skydive-selenium-tests

**Comment by safchain** [comment]
run cdd-overview

**Pull request merged**
