### PR TITLE
runc: handle string or int64 for init_process_pid

### PR DESCRIPTION
**Pull request by safchain**
prior to this commit it was string
75d98b26b7acb0023b990a7305a2553c6dbc12d4

### CODE REVIEW

**Comment by safchain** [comment]
rerun skydive-functional-tests-backend-elasticsearch

**Comment by safchain** [comment]
rerun skydive-k8s-tests

**Comment by safchain** [comment]
run skydive-vagrant-tests

**Comment by safchain** [comment]
rerun skydive-k8s-tests

**Comment by safchain** [comment]
rerun  skydive-vagrant-tests

**Comment by safchain** [comment]
rerun skydive-vagrant-tests

**Comment by lebauce** [comment]
run skydive-scale-tests

**Pull request merged**
