### PR TITLE
Cleaned up OpenShift template

### PR DESCRIPTION
**Pull request by garethahealy**
Removed not needed fields and added liveness/readiness checks to ES/web

### CODE REVIEW

**Comment by safchain** [comment]
Hi Gareth,

Thanks for your contribution !

We use software factory(http://softwarefactory-project.io/r/#/q/project:skydive) for contributions which leverages Gerrit. Could you please submit a review instead of PR following the steps explained in the documentation: http://skydive-project.github.io/skydive/contributing/

If you have any issue you can reach out us on IRC.

Thanks

**Comment by garethahealy** [comment]
@safchain I've done as described in the docs, but get the following error:

localhost:skydive garethah$ git review
Could not connect to gerrit.
Enter your gerrit username: garethahealy
Trying again with ssh://garethahealy@softwarefactory-project.io:29418/skydive
<traceback object at 0x108a0bcb0>
We don't know where your gerrit is. Please manually create a remote
named "gerrit" and try again.
Could not connect to gerrit at ssh://garethahealy@softwarefactory-project.io:29418/skydive
Traceback (most recent call last):
  File "/usr/local/bin/git-review", line 11, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/git_review/cmd.py", line 1534, in main
    sys.exit(e.EXIT_CODE)
AttributeError: 'GitReviewException' object has no attribute 'EXIT_CODE'

Any tips as to what i might be doing wrong?

**Comment by safchain** [comment]
@garethahealy 

can you check that your public ssh key has been imported correctly by software factory in case of using your github account ?  you can check your account settings in order to see keys.

did you do : "git review -s" before "git review" ?

**Comment by garethahealy** [comment]
https://softwarefactory-project.io/r/6128

**Pull request closed without merging**
