### PR TITLE
ci: reduced code duplication in cleanup.sh

### PR DESCRIPTION
**Pull request by hunchback**
This patch removed code duplication in `cleanup.sh` implementation - specifically using newly created functions `cleanup_items` and `snapshot_items` for eliminating most of the common code.

To that the patch introduced no depredations you can run: 

```
# save your baseline
$ sudo scripts/ci/cleanup.sh init

# create and delete newly created items
... add netns, intf, bridge, docker, docker-images
$ sudo scripts/ci/cleanup.sh snapshot
$ sudo scripts/ci/cleanup.sh cleanup 2>&1 | tee run1.log

# attempt to delete items ... none should exist
$ sudo scripts/ci/cleanup.sh snapshot
$ sodo scripts/ci/cleanup.sh cleanup 2>&1 | tee run2.log
```

### CODE REVIEW

**Comment by hunchback** [comment]
@lebauce - the test failure does not appear directly related to my change - please check:

```
16:09:05.926 === RUN   TestSubscription
16:09:05.926 2017-12-02T17:08:58.807+0100	INFO	http/server.go:133 (*Server).Listen	dpdk2: Listening on TCP socket localhost:59999
16:09:05.926 2017-12-02T17:08:58.823+0100	INFO	http/wsserver.go:55 defaultIncomerHandler	dpdk2: New WebSocket Connection from 127.0.0.1:57054 : URI path /wstest
16:09:05.926 2017-12-02T17:08:58.825+0100	INFO	http/wsclient.go:425 (*WSClient).connect	dpdk2: Connected to ws://localhost:59999/wstest
16:09:05.926 ==================
16:09:05.926 WARNING: DATA RACE
16:09:05.926 Read at 0x00c4200b08a0 by goroutine 51:
16:09:05.926   runtime.chansend()
16:09:05.926       /var/lib/jenkins/.gimme/versions/go1.9.1.linux.amd64/src/runtime/chan.go:128 +0x0
16:09:05.926   github.com/skydive-project/skydive/http.(*WSConn).run.func1()
16:09:05.926       /var/lib/jenkins/workspace/skydive-unit-tests/src/github.com/skydive-project/skydive/http/wsclient.go:272 +0x6d
16:09:05.926 
16:09:05.926 Previous write at 0x00c4200b08a0 by goroutine 44:
16:09:05.926   runtime.closechan()
16:09:05.926       /var/lib/jenkins/.gimme/versions/go1.9.1.linux.amd64/src/runtime/chan.go:313 +0x0
16:09:05.926   github.com/skydive-project/skydive/http.(*WSConn).Disconnect()
16:09:05.926       /var/lib/jenkins/workspace/skydive-unit-tests/src/github.com/skydive-project/skydive/http/wsclient.go:348 +0x11e
16:09:05.926   github.com/skydive-project/skydive/http.(*wsIncomingClient).Disconnect()
16:09:05.926       <autogenerated>:1 +0x52
16:09:05.926   github.com/skydive-project/skydive/http.(*WSPool).DisconnectAll()
16:09:05.926       /var/lib/jenkins/workspace/skydive-unit-tests/src/github.com/skydive-project/skydive/http/pool.go:194 +0xfe
16:09:05.926   github.com/skydive-project/skydive/http.(*WSPool).Run()
16:09:05.926       /var/lib/jenkins/workspace/skydive-unit-tests/src/github.com/skydive-project/skydive/http/pool.go:290 +0x44d
16:09:05.926 
16:09:05.926 Goroutine 51 (running) created at:
16:09:05.926   github.com/skydive-project/skydive/http.(*WSConn).run()
16:09:05.926       /var/lib/jenkins/workspace/skydive-unit-tests/src/github.com/skydive-project/skydive/http/wsclient.go:262 +0x9d
16:09:05.926 
16:09:05.926 Goroutine 44 (finished) created at:
16:09:05.926   github.com/skydive-project/skydive/http.(*WSPool).Start()
16:09:05.926       /var/lib/jenkins/workspace/skydive-unit-tests/src/github.com/skydive-project/skydive/http/pool.go:308 +0x7a
16:09:05.926   github.com/skydive-project/skydive/http.TestSubscription()
16:09:05.926       /var/lib/jenkins/workspace/skydive-unit-tests/src/github.com/skydive-project/skydive/http/wsserver_test.go:90 +0x2ea
16:09:05.926   testing.tRunner()
16:09:05.926       /var/lib/jenkins/.gimme/versions/go1.9.1.linux.amd64/src/testing/testing.go:746 +0x16c
16:09:05.926 ==================
16:09:05.926 panic: send on closed channel
16:09:05.926 
16:09:05.926 goroutine 36 [running]:
16:09:05.926 github.com/skydive-project/skydive/http.(*WSConn).run.func1(0xc42077a1c0)
16:09:05.926 	/var/lib/jenkins/workspace/skydive-unit-tests/src/github.com/skydive-project/skydive/http/wsclient.go:272 +0x6e
16:09:05.926 created by github.com/skydive-project/skydive/http.(*WSConn).run
16:09:05.926 	/var/lib/jenkins/workspace/skydive-unit-tests/src/github.com/skydive-project/skydive/http/wsclient.go:262 +0x9e
16:09:05.926 FAIL	github.com/skydive-project/skydive/http	2.059s
16:09:05.926 ?   	github.com/skydive-project/skydive/logging	[no test files]
```

**Comment by safchain** [comment]
The pr #643 will fix this issue

**Comment by hunchback** [comment]
@safchain - ok once #643 is merged I'll rebase ...

**Comment by lebauce** [comment]
@hunchback It's now merged

**Comment by hunchback** [comment]
The test failed again, does not appear related to my fix @lebauce please check:

```
12:47:16.876 === RUN   TestWSMessageSubscription
12:47:16.876 2017-12-04T13:47:08.779+0100	INFO	http/server.go:133 (*Server).Listen	dpdk3: Listening on TCP socket localhost:59999
12:47:16.876 2017-12-04T13:47:08.800+0100	INFO	http/wsclient.go:425 (*WSClient).connect	dpdk3: Connected to ws://localhost:59999/wstest
12:47:16.876 2017-12-04T13:47:08.802+0100	INFO	http/wsserver.go:55 defaultIncomerHandler	dpdk3: New WebSocket Connection from 127.0.0.1:33186 : URI path /wstest
12:47:16.876 ==================
12:47:16.876 WARNING: DATA RACE
12:47:16.876 Read at 0x00c4205a21a8 by goroutine 36:
12:47:16.876   github.com/skydive-project/skydive/http.(*WSConn).run()
12:47:16.876       /var/lib/jenkins/workspace/skydive-unit-tests/src/github.com/skydive-project/skydive/http/wsclient.go:315 +0x1b7
12:47:16.876 
12:47:16.876 Previous write at 0x00c4205a21a8 by goroutine 32:
12:47:16.876   github.com/skydive-project/skydive/http.(*wsIncomingClient).upgradeToWSJSONSpeaker()
12:47:16.876       /var/lib/jenkins/workspace/skydive-unit-tests/src/github.com/skydive-project/skydive/http/wsjson.go:307 +0x7b
12:47:16.876   github.com/skydive-project/skydive/http.NewWSJSONServer.func1()
12:47:16.876       /var/lib/jenkins/workspace/skydive-unit-tests/src/github.com/skydive-project/skydive/http/wsjson.go:399 +0x84
12:47:16.876   github.com/skydive-project/skydive/http.(*WSServer).serveMessages()
12:47:16.876       /var/lib/jenkins/workspace/skydive-unit-tests/src/github.com/skydive-project/skydive/http/wsserver.go:86 +0x22e
12:47:16.876   github.com/skydive-project/skydive/http.(*WSServer).(github.com/skydive-project/skydive/http.serveMessages)-fm()
12:47:16.876       /var/lib/jenkins/workspace/skydive-unit-tests/src/github.com/skydive-project/skydive/http/wsserver.go:104 +0x5f
12:47:16.876   github.com/skydive-project/skydive/http.(*NoAuthenticationBackend).Wrap.func1()
12:47:16.876       /var/lib/jenkins/workspace/skydive-unit-tests/src/github.com/skydive-project/skydive/http/noauth.go:44 +0x160
12:47:16.876   net/http.HandlerFunc.ServeHTTP()
12:47:16.876       /var/lib/jenkins/.gimme/versions/go1.9.1.linux.amd64/src/net/http/server.go:1918 +0x51
12:47:16.876   github.com/skydive-project/skydive/vendor/github.com/gorilla/mux.(*Router).ServeHTTP()
12:47:16.876       /var/lib/jenkins/workspace/skydive-unit-tests/src/github.com/skydive-project/skydive/vendor/github.com/gorilla/mux/mux.go:100 +0x363
12:47:16.876   net/http.serverHandler.ServeHTTP()
12:47:16.876       /var/lib/jenkins/.gimme/versions/go1.9.1.linux.amd64/src/net/http/server.go:2619 +0xbc
12:47:16.876   net/http.(*conn).serve()
12:47:16.876       /var/lib/jenkins/.gimme/versions/go1.9.1.linux.amd64/src/net/http/server.go:1801 +0x83b
12:47:16.876 
12:47:16.876 Goroutine 36 (running) created at:
12:47:16.876   github.com/skydive-project/skydive/http.(*WSConn).start()
12:47:16.876       /var/lib/jenkins/workspace/skydive-unit-tests/src/github.com/skydive-project/skydive/http/wsclient.go:255 +0x6c
12:47:16.876   github.com/skydive-project/skydive/http.defaultIncomerHandler()
12:47:16.876       /var/lib/jenkins/workspace/skydive-unit-tests/src/github.com/skydive-project/skydive/http/wsserver.go:58 +0x1f0
12:47:16.876   github.com/skydive-project/skydive/http.NewWSJSONServer.func1()
12:47:16.876       /var/lib/jenkins/workspace/skydive-unit-tests/src/github.com/skydive-project/skydive/http/wsjson.go:399 +0x76
12:47:16.876   github.com/skydive-project/skydive/http.(*WSServer).serveMessages()
12:47:16.876       /var/lib/jenkins/workspace/skydive-unit-tests/src/github.com/skydive-project/skydive/http/wsserver.go:86 +0x22e
12:47:16.876   github.com/skydive-project/skydive/http.(*WSServer).(github.com/skydive-project/skydive/http.serveMessages)-fm()
12:47:16.876       /var/lib/jenkins/workspace/skydive-unit-tests/src/github.com/skydive-project/skydive/http/wsserver.go:104 +0x5f
12:47:16.876   github.com/skydive-project/skydive/http.(*NoAuthenticationBackend).Wrap.func1()
12:47:16.876       /var/lib/jenkins/workspace/skydive-unit-tests/src/github.com/skydive-project/skydive/http/noauth.go:44 +0x160
12:47:16.876   net/http.HandlerFunc.ServeHTTP()
12:47:16.876       /var/lib/jenkins/.gimme/versions/go1.9.1.linux.amd64/src/net/http/server.go:1918 +0x51
12:47:16.876   github.com/skydive-project/skydive/vendor/github.com/gorilla/mux.(*Router).ServeHTTP()
12:47:16.876       /var/lib/jenkins/workspace/skydive-unit-tests/src/github.com/skydive-project/skydive/vendor/github.com/gorilla/mux/mux.go:100 +0x363
12:47:16.876   net/http.serverHandler.ServeHTTP()
12:47:16.876       /var/lib/jenkins/.gimme/versions/go1.9.1.linux.amd64/src/net/http/server.go:2619 +0xbc
12:47:16.876   net/http.(*conn).serve()
12:47:16.876       /var/lib/jenkins/.gimme/versions/go1.9.1.linux.amd64/src/net/http/server.go:1801 +0x83b
12:47:16.876 
12:47:16.876 Goroutine 32 (running) created at:
12:47:16.876   net/http.(*Server).Serve()
12:47:16.876       /var/lib/jenkins/.gimme/versions/go1.9.1.linux.amd64/src/net/http/server.go:2720 +0x37c
12:47:16.876   github.com/skydive-project/skydive/http.(*Server).Serve()
12:47:16.876       /var/lib/jenkins/workspace/skydive-unit-tests/src/github.com/skydive-project/skydive/http/server.go:150 +0x127
12:47:16.876 ==================
12:47:16.876 ==================
12:47:16.876 WARNING: DATA RACE
12:47:16.876 Read at 0x00c42058c300 by goroutine 37:
12:47:16.876   runtime.chansend()
12:47:16.876       /var/lib/jenkins/.gimme/versions/go1.9.1.linux.amd64/src/runtime/chan.go:128 +0x0
12:47:16.876   github.com/skydive-project/skydive/http.(*WSConn).run.func1()
12:47:16.876       /var/lib/jenkins/workspace/skydive-unit-tests/src/github.com/skydive-project/skydive/http/wsclient.go:272 +0x6d
12:47:16.876 
12:47:16.876 Previous write at 0x00c42058c300 by goroutine 12:
12:47:16.876   runtime.closechan()
12:47:16.876       /var/lib/jenkins/.gimme/versions/go1.9.1.linux.amd64/src/runtime/chan.go:313 +0x0
12:47:16.876   github.com/skydive-project/skydive/http.(*WSConn).Disconnect()
12:47:16.876       /var/lib/jenkins/workspace/skydive-unit-tests/src/github.com/skydive-project/skydive/http/wsclient.go:348 +0x11e
12:47:16.876   github.com/skydive-project/skydive/http.(*wsIncomingClient).Disconnect()
12:47:16.876       <autogenerated>:1 +0x52
12:47:16.876   github.com/skydive-project/skydive/http.(*WSJSONSpeaker).Disconnect()
12:47:16.876       <autogenerated>:1 +0x57
12:47:16.876   github.com/skydive-project/skydive/http.(*WSPool).DisconnectAll()
12:47:16.876       /var/lib/jenkins/workspace/skydive-unit-tests/src/github.com/skydive-project/skydive/http/pool.go:194 +0xfe
12:47:16.876   github.com/skydive-project/skydive/http.(*WSPool).Run()
12:47:16.876       /var/lib/jenkins/workspace/skydive-unit-tests/src/github.com/skydive-project/skydive/http/pool.go:290 +0x44d
12:47:16.876 
12:47:16.876 Goroutine 37 (running) created at:
12:47:16.876   github.com/skydive-project/skydive/http.(*WSConn).run()
12:47:16.876       /var/lib/jenkins/workspace/skydive-unit-tests/src/github.com/skydive-project/skydive/http/wsclient.go:262 +0x9d
12:47:17.040 
12:47:17.040 Goroutine 12 (finished) created at:
12:47:17.040   github.com/skydive-project/skydive/http.(*WSPool).Start()
12:47:17.040       /var/lib/jenkins/workspace/skydive-unit-tests/src/github.com/skydive-project/skydive/http/pool.go:308 +0x7a
12:47:17.040   github.com/skydive-project/skydive/http.TestWSMessageSubscription()
12:47:17.040       /var/lib/jenkins/workspace/skydive-unit-tests/src/github.com/skydive-project/skydive/http/wsmessage_test.go:100 +0x3ee
12:47:17.040   testing.tRunner()
12:47:17.040       /var/lib/jenkins/.gimme/versions/go1.9.1.linux.amd64/src/testing/testing.go:746 +0x16c
12:47:17.040 ==================
12:47:17.040 panic: send on closed channel
12:47:17.040 
12:47:17.040 goroutine 26 [running]:
12:47:17.040 github.com/skydive-project/skydive/http.(*WSConn).run.func1(0xc4205a20e0)
12:47:17.040 	/var/lib/jenkins/workspace/skydive-unit-tests/src/github.com/skydive-project/skydive/http/wsclient.go:272 +0x6e
12:47:17.040 created by github.com/skydive-project/skydive/http.(*WSConn).run
12:47:17.040 	/var/lib/jenkins/workspace/skydive-unit-tests/src/github.com/skydive-project/skydive/http/wsclient.go:262 +0x9e
12:47:17.040 FAIL	github.com/skydive-project/skydive/http	5.055s
12:47:17.040 ?   	github.com/skydive-project/skydive/logging	[no test files]
```

**Comment by safchain** [comment]
@hunchback you need to rebase on top of master, having only one commit

**Comment by hunchback** [comment]
@safchain - done

**Comment by hunchback** [comment]
Still getting:

```
14:15:58.976 panic: send on closed channel
14:15:58.976 
14:15:58.976 goroutine 50 [running]:
14:15:58.976 github.com/skydive-project/skydive/http.(*WSConn).run.func1(0xc4203601c0)
14:15:58.976 	/var/lib/jenkins/workspace/skydive-unit-tests/src/github.com/skydive-project/skydive/http/wsclient.go:272 +0x6e
14:15:58.976 created by github.com/skydive-project/skydive/http.(*WSConn).run
14:15:58.976 	/var/lib/jenkins/workspace/skydive-unit-tests/src/github.com/skydive-project/skydive/http/wsclient.go:262 +0x9e
14:15:58.976 FAIL	github.com/skydive-project/skydive/http	1.083s
14:15:58.976 ?   	github.com/skydive-project/skydive/logging	[no test files]
```

**Comment by safchain** [comment]
@hunchback master branch seems to be not up to date you need to have at least this patch
https://github.com/skydive-project/skydive/commit/1dfc9cc8193f6244d3fd654b11b11888e31bb693

**Comment by hunchback** [comment]
@safchain - ok did a fresh rebase

**Comment by hunchback** [comment]
@safchain - failed with the following:

```
08:43:49.858 === RUN   TestWSMessageSubscription
08:43:49.858 2017-12-05T09:43:41.705+0100	INFO	http/server.go:133 (*Server).Listen	dpdk1: Listening on TCP socket localhost:59999
08:43:49.858 2017-12-05T09:43:41.726+0100	INFO	http/wsserver.go:55 defaultIncomerHandler	dpdk1: New WebSocket Connection from 127.0.0.1:58686 : URI path /wstest
08:43:49.858 2017-12-05T09:43:41.726+0100	INFO	http/wsclient.go:425 (*WSClient).connect	dpdk1: Connected to ws://localhost:59999/wstest
08:43:49.858 --- PASS: TestWSMessageSubscription (1.02s)
08:43:49.858 === RUN   TestSubscription
08:43:49.858 2017-12-05T09:43:42.726+0100	INFO	http/server.go:133 (*Server).Listen	dpdk1: Listening on TCP socket localhost:59999
08:43:49.858 2017-12-05T09:43:42.751+0100	INFO	http/wsserver.go:55 defaultIncomerHandler	dpdk1: New WebSocket Connection from 127.0.0.1:58690 : URI path /wstest
08:43:49.858 2017-12-05T09:43:42.751+0100	INFO	http/wsclient.go:425 (*WSClient).connect	dpdk1: Connected to ws://localhost:59999/wstest
08:43:49.858 --- FAIL: TestSubscription (5.02s)
08:43:49.858 	wsserver_test.go:142: Server should have received 2 OnMessage event: 0
08:43:49.858 FAIL
08:43:49.858 FAIL	github.com/skydive-project/skydive/http	6.074s
08:43:49.858 ?   	github.com/skydive-project/skydive/logging	[no test files]
```

**Comment by safchain** [comment]
rerun unit-tests

**Comment by hunchback** [comment]
@safchain - ok some can this PR be merged?

**Comment by safchain** [comment]
@hunchback just testing one more time and I will merge it

**Comment by safchain** [comment]
rerun test

**Pull request merged**
