### PR TITLE
pi: improve the packet injector error messages

### PR DESCRIPTION
**Pull request by masco-enovance**

### CODE REVIEW

**Comment by safchain** [comment]
rerun functional-tests-backend-orientdb

**Comment by lebauce** [comment]
run skydive-functional-tests-backend-orientdb

**Comment by lebauce** [comment]
@masco-enovance Can you please rebase against master ? (to avoid the CI fail)

**Comment by safchain** [comment]
rerun functional-tests-backend-orientdb

**Comment by safchain** [comment]
rerun functional-tests-backend-orientdb

**Comment by safchain** [comment]
rerun functional-tests-backend-orientdb

**Pull request merged**
