### PR TITLE
ui config cleanup and add default highlight/filter config parameter

### PR DESCRIPTION
**Pull request by safchain**

### CODE REVIEW

**Comment by safchain** [comment]
rerun functional-tests-backend-orientdb

**Comment by safchain** [comment]
rerun selenium-tests

**Comment by safchain** [comment]
run cdd-overview

**Comment by safchain** [comment]
rerun functional-tests-backend-orientdb

**Comment by hunchback** [comment]
@safchain - fine - closing the PR

**Comment by safchain** [comment]
rerun functional-tests-backend-orientdb

**Pull request merged**
