### PR TITLE
CI : skip jobs on PR comment

### PR DESCRIPTION
**Pull request by nplanel**
skip skydive-go-fmt

### CODE REVIEW

**Comment by safchain** [comment]
I think there is already something check here:
https://github.com/janinko/ghprb#--114

```
[skip ci]
```

**Comment by nplanel** [comment]
seems to have no effect on our CI, futhermore the idea was to disable only some on the jobs not all

**Comment by nplanel** [comment]
run skydive-selenium-tests

**Comment by nplanel** [comment]
run skydive-unit-tests

**Comment by nplanel** [comment]
skip skydive-unit-tests

**Comment by nplanel** [comment]
run tests

**Comment by nplanel** [comment]
run skydive-unit-tests

**Comment by nplanel** [comment]
run skydive-compile-tests

**Comment by nplanel** [comment]
rerun skydive-compile-tests

**Comment by nplanel** [comment]
run tests

**Comment by nplanel** [comment]
run skydive-functional-tests-backend-elasticsearch

**Comment by lebauce** [comment]
It seems [skip ci] needs to be put inside the body of the PR description

**Comment by nplanel** [comment]
I tried and it wasn't working (tu put [skip ci])
furthermore I would to disable only some of the jobs, not all, so at each push only "mandatory" jobs will be executed
I already tested it with skydive-go-fmt and skydive-unti-tests
working well, the only think they need to be on the 1st line of the 1st GH message, ex  
"skip skydive-go-fmt skip skydive-unti-tests"

**Pull request merged**
