### PR TITLE
UI: Automatically PIN Fabric, Hosts and ns nodes

### PR DESCRIPTION
**Pull request by eranra**
This patch automatically PINs Fabric, Hosts and ns nodes.

WIP at this stage.

### CODE REVIEW

**Comment by safchain** [comment]
ok to test

**Comment by safchain** [comment]
add to whitelist

**Comment by safchain** [comment]
run cdd-overview

**Comment by lebauce** [comment]
Can we close this one ?

**Comment by lebauce** [comment]
Closing it as it hasn't moved in a while. Please reopen if necessary

**Pull request closed without merging**
