### PR TITLE
ansible: simple module to query skydive

### PR DESCRIPTION
**Pull request by pierrecregut**
Sends a gremlin query to a skydive analyzer, the result is a list of
nodes/edges in json format.

### CODE REVIEW

**Comment by pierrecregut** [comment]
Typical use: query host/interface nodes to make the glue between the fabric retrieved by skydive and the nodes where agents run.

**Comment by pierrecregut** [comment]
run skydive-k8s-tests

**Comment by pierrecregut** [comment]
run skydive-k8s-tests

**Comment by safchain** [comment]
run skydive-k8s-tests

**Pull request merged**
