### PR TITLE
objectstore: specify protobuf as client protocol

### PR DESCRIPTION
**Pull request by safchain**
Fixes: #1625

### CODE REVIEW

**Comment by safchain** [comment]
@orozery can you please confirm that it fixes the issue ? thanks

**Comment by orozery** [comment]
@safchain different error now:
```2019-01-28T14:19:57.005+0200    ERROR   websocket/message.go:389 (*StructSpeaker).OnMessage     ubuntu: Error while decoding Protobuf StructMessage proto: wrong wireType = 2 for field Format```

**Comment by safchain** [comment]
@orozery ok I guess that is because the skydive and the subscriber are not aligned, going to change the subscriber to json

**Comment by safchain** [comment]
@orozery can you give another try ? thanks

**Comment by orozery** [comment]
@safchain still no good:
```2019-01-28T14:46:57.270+0200    ERROR   subscriber/objectstore.go:43 (*Subscriber).OnStructMessage      ubuntu: Failed to unmarshal flows:  parse error: expected { near offset 1 of ''```

**Comment by safchain** [comment]
@orozery I hope this one will be OK :)

**Pull request merged**
