### PR TITLE
ansible: bug - different websocket host_id

### LINKED ISSUE #1484: ansible: support multi-threading
When skydive_node.py or skydive_edge.py are used in an ansible playbook, it is necessary to set --fork=1

### PR DESCRIPTION
**Pull request by pierrecregut**
Generates a host_id based on the host parameter. Necessary to avoid
conflicts on the analyzer.

Adds some notes and fixes some minor problems in the online
documentation.

closes #1484

### CODE REVIEW

**Comment by pierrecregut** [comment]
The commit solves the problem, but is not perfect. The missing point is that even with a bug, ansible should have failed but not hanged. The analyzer has sent an error message but it is swallowed somewhere.

**Comment by safchain** [comment]
Correct, I think that is more a python skydive library issue than ansible module

**Comment by pierrecregut** [comment]
Anyway, the fix is not enough even if it often works. There are still some conflicts sometimes during the second phase that enumerates the ports. My guess is that the loop gives work items to different workers with may be an affinity that hides the problem most of the time. 

Is there a good reason for not using a random id as X-Host-id ? A simple fix is to add os.getpid()

**Comment by safchain** [comment]
No good reason getpid is fine

**Comment by pierrecregut** [comment]
run skydive-unit-tests

**Comment by pierrecregut** [comment]
unit tests are dependent on the availability of the mawi server in japan.

**Comment by safchain** [comment]
rerun skydive-unit-tests

**Comment by safchain** [comment]
rerun skydive-unit-tests

**Pull request merged**
