### PR TITLE
vagrant: add support for OpenStack provider

### PR DESCRIPTION
**Pull request by lebauce**

### CODE REVIEW

**Comment by lebauce** [comment]
run skydive-kolla-tests

**Comment by lebauce** [comment]
run skydive-kolla-tests

**Comment by lebauce** [comment]
run skydive-devstack

**Comment by lebauce** [comment]
run skydive-kolla-tests

**Comment by lebauce** [comment]
run skydive-devstack-tests

**Comment by lebauce** [comment]
run skydive-devstack-tests

**Comment by lebauce** [comment]
run skydive-devstack-tests

**Comment by safchain** [comment]
rerun go-fmt

**Comment by lebauce** [comment]
run skydive-kolla-tests

**Comment by lebauce** [comment]
run skydive-kolla-tests

**Comment by lebauce** [comment]
run skydive-vagrant-tests

**Comment by lebauce** [comment]
run skydive-vagrant-tests

**Comment by lebauce** [comment]
run skydive-kolla-tests

**Comment by lebauce** [comment]
run skydive-vagrant-tests

**Comment by lebauce** [comment]
run skydive-vagrant-tests

**Comment by lebauce** [comment]
run skydive-vagrant-tests

**Comment by lebauce** [comment]
run skydive-kolla-tests

**Comment by lebauce** [comment]
run skydive-kolla-tests

**Comment by lebauce** [comment]
run run skydive-vagrant-tests

**Comment by lebauce** [comment]
run skydive-devstack-tests

**Comment by lebauce** [comment]
run skydive-devstack-tests

**Comment by safchain** [comment]
run devstack

**Comment by safchain** [comment]
rerun devstack

**Comment by safchain** [comment]
rerun devstack-tests

**Comment by safchain** [comment]
rerun devstack-tests

**Comment by lebauce** [comment]
run skydive-kolla-tests

**Pull request merged**
