### PR TITLE
ui: don't strip node hostname

### PR DESCRIPTION
**Pull request by eonpatapon**

### CODE REVIEW

**Comment by eonpatapon** [comment]
Avoid to strip a hostname that is > 12 chars]

**Comment by safchain** [comment]
ok to tests

**Comment by safchain** [comment]
rerun tests

**Comment by safchain** [comment]
rerun selenium-tests

**Comment by masco-enovance** [comment]
rerun selenium-tests

**Comment by safchain** [comment]
rerun selenium-tests

**Pull request merged**
