### PR TITLE
python: add capture API

### PR DESCRIPTION
**Pull request by nlewo**
Note I did not run the included python tests suite (even if I tryied a bit):/

### CODE REVIEW

**Comment by nplanel** [comment]
run skydive-python

**Comment by nplanel** [comment]
run skydive-python-tests

**Comment by nlewo** [comment]
run skydive-python-tests

**Comment by safchain** [comment]
run skydive-python-tests

**Comment by nplanel** [comment]
run skydive-unit-tests

**Comment by nlewo** [comment]
run skydive-unit-tests

**Comment by nplanel** [comment]
run skydive-python-tests

**Comment by nplanel** [comment]
run skydive-python-tests

**Comment by nplanel** [comment]
run skydive-compile-tests

**Comment by nplanel** [comment]
run skydive-unit-tests

**Comment by nplanel** [comment]
run-tests

**Comment by nplanel** [comment]
run tests

**Comment by nplanel** [comment]
run skydive-python-tests

**Comment by nplanel** [comment]
run skydive-selenium-tests

**Comment by nplanel** [comment]
run skydive-functional-tests-backend-orientdb

**Pull request merged**
