### PR TITLE
k8s: added cronjob probe

### PR DESCRIPTION
**Pull request by hunchback**
To test enable k8s probe and run:

```
kubectl create -f tests/k8s/cronjob.yaml
```

### CODE REVIEW

**Comment by hunchback** [comment]
run skydive-ppc64le-tests

**Comment by lebauce** [comment]
I don't see anything related to cronjob, is it normal ?

**Comment by hunchback** [comment]
@lebauce - oops, sorry I pushed the wrong branch - should be ok now

**Comment by lebauce** [comment]
I understand that the goal is the insert the Kubernetes resources into Skydive but will there ever be any use case around cronjob ?

**Comment by hunchback** [comment]
Yes, its' part of representing the workload related view of k8s (existing
in comparable tools hence required so as to to have needless parity)

**Pull request merged**
