### PR TITLE
CI : avoid configuring jenkins slaves/master during the deployment

### PR DESCRIPTION
**Pull request by nplanel**

### CODE REVIEW

**Comment by safchain** [comment]
run skydive-functional-hw-tests

**Comment by nplanel** [comment]
run skydive-functional-hw-tests

**Comment by nplanel** [comment]
run skydive-functional-hw-tests

**Comment by safchain** [comment]
run skydive-functional-hw-tests

**Comment by nplanel** [comment]
run skydive-functional-hw-tests

**Pull request merged**
