### PR TITLE
Fix es rolling index

### PR DESCRIPTION
**Pull request by safchain**

### CODE REVIEW

**Comment by safchain** [comment]
run tripleo-tests

**Comment by safchain** [comment]
run tripleo-tests

**Comment by safchain** [comment]
run tripleo-tests

**Comment by safchain** [comment]
run tests

**Comment by safchain** [comment]
run skydive-go-fmt

**Comment by safchain** [comment]
rerun functional-tests-backend-elasticsearch

**Comment by safchain** [comment]
rerun functional-tests-backend-elasticsearch

**Comment by safchain** [comment]
rerun functional-tests-backend-elasticsearch

**Comment by safchain** [comment]
rerun functional-tests-backend-elasticsearch

**Comment by safchain** [comment]
run devstack-tests

**Comment by safchain** [comment]
run vagrant-tests

**Comment by safchain** [comment]
run devstack-tests

**Comment by safchain** [comment]
run devstack-tests

**Comment by lebauce** [comment]
run vagrant-tests

**Comment by safchain** [comment]
run devstack-tests

**Comment by safchain** [comment]
run devstack-tests

**Comment by safchain** [comment]
run devstack-tests

**Comment by safchain** [comment]
run devstack-tests

**Comment by safchain** [comment]
rerun unit-tests

**Comment by safchain** [comment]
run devstack-tests

**Comment by safchain** [comment]
rerun devstack-tests

**Comment by safchain** [comment]
run skydive-devstack-tests

**Pull request merged**
